In [63]:
# Dataset: https://www.kaggle.com/datasets/rmisra/news-category-dataset

In [64]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense 
from sklearn.model_selection import train_test_split
import pickle

### Date gathering

In [65]:
data = pd.read_json('News_Category_Dataset_v3.json', lines=True)

### Data exploration

In [66]:
data

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [67]:
data.shape

(209527, 6)

In [68]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [69]:
# We need only the short description for our next word prediction task. So we will drop the other columns.
data = data[['short_description']][:1000]

In [70]:
data

                                     short_description
0    Health experts said it is too early to predict...
1    He was subdued by passengers and crew when he ...
2    "Until you have a dog you don't understand wha...
3    "Accidentally put grown-up toothpaste on my to...
4    Amy Cooper accused investment firm Franklin Te...
..                                                 ...
995  The change does not appear imminent as the gov...
996  World leaders have been calling for an investi...
997  Assad's office said he met with Sheikh Mohamed...
998  The 7.4-magnitude temblor knocked out power an...
999  Two Canadian students were also hospitalized i...

[1000 rows x 1 columns]

### Check null and duplicate columns and remove it

In [71]:
# Check null values
data.isnull().sum()

short_description    0
dtype: int64

In [72]:
# Check duplicates
data.duplicated().sum()

np.int64(0)

In [73]:
# Drop duplicates
data.drop_duplicates(inplace=True)

In [74]:
# Check duplicates after remove it
data.duplicated().sum()

np.int64(0)

### Date preprocessing

In [75]:
tokenizer = Tokenizer(oov_token='<OOV>')

In [76]:
# Fit the tokenizer on the short descriptions
tokenizer.fit_on_texts(data['short_description'])

In [77]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'a': 3,
 'to': 4,
 'of': 5,
 'in': 6,
 'and': 7,
 'for': 8,
 'on': 9,
 'that': 10,
 'was': 11,
 'is': 12,
 'said': 13,
 'with': 14,
 'as': 15,
 'his': 16,
 'at': 17,
 'has': 18,
 'an': 19,
 'after': 20,
 'from': 21,
 'her': 22,
 'it': 23,
 'he': 24,
 'who': 25,
 'new': 26,
 'will': 27,
 'are': 28,
 'by': 29,
 'have': 30,
 'about': 31,
 '”': 32,
 'be': 33,
 'u': 34,
 'president': 35,
 's': 36,
 'former': 37,
 'more': 38,
 'this': 39,
 'one': 40,
 'people': 41,
 'two': 42,
 'their': 43,
 '—': 44,
 'you': 45,
 'year': 46,
 'were': 47,
 'not': 48,
 'trump': 49,
 'when': 50,
 'but': 51,
 'they': 52,
 'over': 53,
 'been': 54,
 'house': 55,
 'into': 56,
 'up': 57,
 'out': 58,
 'told': 59,
 'first': 60,
 'than': 61,
 'i': 62,
 'its': 63,
 'against': 64,
 'she': 65,
 'or': 66,
 'police': 67,
 'russian': 68,
 'say': 69,
 'how': 70,
 'star': 71,
 'also': 72,
 'last': 73,
 'what': 74,
 'could': 75,
 'had': 76,
 'biden': 77,
 'ukraine': 78,
 'white': 79,
 'court': 80,
 'show': 81,
 'day': 82,
 'man': 83,
 'which': 84,
 'during': 85,
 'some': 86,
 'actor': 87,
 'no': 88,
 'says': 89,
 'years': 90,
 'now': 91,
 'all': 92,
 'abortion': 93,
 'your': 94,
 'gop': 95,
 'war': 96,
 'other': 97,
 'life': 98,
 'can': 99,
 'city': 100,
 'million': 101,
 'like': 102,
 'old': 103,
 'republican': 104,
 'york': 105,
 'donald': 106,
 'three': 107,
 'him': 108,
 'state': 109,
 'killed': 110,
 'since': 111,
 'if': 112,
 'only': 113,
 'my': 114,
 'american': 115,
 'school': 116,
 'made': 117,
 'so': 118,
 'many': 119,
 'called': 120,
 'accused': 121,
 'officials': 122,
 'series': 123,
 'there': 124,
 'time': 125,
 'election': 126,
 'host': 127,
 'off': 128,
 'attack': 129,
 'being': 130,
 'health': 131,
 'world': 132,
 'joe': 133,
 'federal': 134,
 'children': 135,
 'even': 136,
 'should': 137,
 'social': 138,
 "trump's": 139,
 'just': 140,
 'back': 141,
 'office': 142,
 'week': 143,
 'government': 144,
 'where': 145,
 'sunday': 146,
 '000': 147,
 'reported': 148,
 'water': 149,
 'service': 150,
 'days': 151,
 'music': 152,
 'under': 153,
 '6': 154,
 'black': 155,
 '10': 156,
 'media': 157,
 'care': 158,
 'we': 159,
 'law': 160,
 'ukrainian': 161,
 'shooting': 162,
 'texas': 163,
 'get': 164,
 'before': 165,
 'would': 166,
 'authorities': 167,
 'support': 168,
 'rights': 169,
 'most': 170,
 'still': 171,
 'public': 172,
 '19': 173,
 'part': 174,
 '2021': 175,
 'capitol': 176,
 'down': 177,
 'five': 178,
 'make': 179,
 '1': 180,
 'news': 181,
 'fire': 182,
 'shows': 183,
 'home': 184,
 'night': 185,
 'wrote': 186,
 'our': 187,
 'supreme': 188,
 'members': 189,
 'national': 190,
 'post': 191,
 'fox': 192,
 'major': 193,
 'while': 194,
 'them': 195,
 'late': 196,
 'georgia': 197,
 'mass': 198,
 'gun': 199,
 'why': 200,
 'group': 201,
 'country': 202,
 "don't": 203,
 'family': 204,
 'russia': 205,
 'nearly': 206,
 'work': 207,
 'reportedly': 208,
 "it's": 209,
 'take': 210,
 'judge': 211,
 'second': 212,
 'friday': 213,
 'run': 214,
 'way': 215,
 'comedy': 216,
 'same': 217,
 'decision': 218,
 'own': 219,
 'according': 220,
 'went': 221,
 'asked': 222,
 'story': 223,
 'campaign': 224,
 'justice': 225,
 'investigating': 226,
 'times': 227,
 'these': 228,
 'known': 229,
 'us': 230,
 '“the': 231,
 'held': 232,
 'may': 233,
 'action': 234,
 'shot': 235,
 'help': 236,
 'announced': 237,
 'me': 238,
 'across': 239,
 'case': 240,
 'latest': 241,
 'rock': 242,
 'next': 243,
 'senate': 244,
 'least': 245,
 'tv': 246,
 'chris': 247,
 'right': 248,
 'experts': 249,
 'whether': 250,
 'video': 251,
 'park': 252,
 'woman': 253,
 'interview': 254,
 'storm': 255,
 'tell': 256,
 'several': 257,
 'want': 258,
 'jan': 259,
 'stage': 260,
 '18': 261,
 'power': 262,
 'movie': 263,
 'general': 264,
 'stop': 265,
 'free': 266,
 'secretary': 267,
 'defense': 268,
 'singer': 269,
 'weekend': 270,
 'violence': 271,
 'long': 272,
 'including': 273,
 '3': 274,
 'ex': 275,
 'covid': 276,
 'person': 277,
 'used': 278,
 'charges': 279,
 'men': 280,
 'women': 281,
 'parents': 282,
 'democratic': 283,
 'comedian': 284,
 'end': 285,
 'too': 286,
 'dog': 287,
 'carolina': 288,
 'found': 289,
 'monday': 290,
 'full': 291,
 'come': 292,
 'leaders': 293,
 'conservative': 294,
 'died': 295,
 'four': 296,
 'governor': 297,
 'took': 298,
 "russia's": 299,
 '2020': 300,
 'information': 301,
 'administration': 302,
 'led': 303,
 'film': 304,
 'investigation': 305,
 'awards': 306,
 'ceremony': 307,
 '5': 308,
 'july': 309,
 'something': 310,
 'grand': 311,
 'california': 312,
 'security': 313,
 'forces': 314,
 'pop': 315,
 'change': 316,
 'high': 317,
 'elementary': 318,
 'uvalde': 319,
 'go': 320,
 'following': 321,
 'might': 322,
 'charged': 323,
 'look': 324,
 'roe': 325,
 'v': 326,
 'child': 327,
 'did': 328,
 'response': 329,
 'top': 330,
 'political': 331,
 'due': 332,
 'getting': 333,
 'showed': 334,
 'democrat': 335,
 'co': 336,
 'became': 337,
 'food': 338,
 'know': 339,
 'young': 340,
 '50': 341,
 'access': 342,
 'live': 343,
 'kids': 344,
 'prime': 345,
 'weeks': 346,
 '4': 347,
 'mexico': 348,
 "here's": 349,
 'number': 350,
 'taken': 351,
 'away': 352,
 'rep': 353,
 'kyiv': 354,
 'early': 355,
 'without': 356,
 'director': 357,
 'past': 358,
 'wife': 359,
 'record': 360,
 'efforts': 361,
 'set': 362,
 'months': 363,
 'reports': 364,
 'issues': 365,
 'never': 366,
 'thousands': 367,
 'despite': 368,
 'received': 369,
 'history': 370,
 'lost': 371,
 'assault': 372,
 'reality': 373,
 'james': 374,
 'program': 375,
 'press': 376,
 'does': 377,
 'red': 378,
 'do': 379,
 'move': 380,
 'homes': 381,
 'taking': 382,
 'both': 383,
 'anti': 384,
 'member': 385,
 'schools': 386,
 'see': 387,
 "he's": 388,
 'teachers': 389,
 'residents': 390,
 'expected': 391,
 'season': 392,
 'americans': 393,
 'wade': 394,
 'leader': 395,
 'trial': 396,
 'sex': 397,
 'order': 398,
 'making': 399,
 'revealed': 400,
 'need': 401,
 'twitter': 402,
 'billion': 403,
 'north': 404,
 'gas': 405,
 'near': 406,
 'committee': 407,
 'deal': 408,
 'official': 409,
 'gov': 410,
 'calling': 411,
 'issue': 412,
 'until': 413,
 'half': 414,
 'insurrection': 415,
 'follows': 416,
 'helped': 417,
 'win': 418,
 'invasion': 419,
 'everything': 420,
 'building': 421,
 'death': 422,
 'false': 423,
 'failed': 424,
 'saturday': 425,
 'doesn’t': 426,
 'running': 427,
 'pandemic': 428,
 'turned': 429,
 'arrived': 430,
 'role': 431,
 'doing': 432,
 'face': 433,
 'play': 434,
 'multiple': 435,
 'based': 436,
 'it’s': 437,
 'threatening': 438,
 'attacks': 439,
 'significant': 440,
 'got': 441,
 'crowd': 442,
 'hope': 443,
 'county': 444,
 'lawsuit': 445,
 'began': 446,
 '30': 447,
 'related': 448,
 'around': 449,
 'comes': 450,
 'between': 451,
 'prince': 452,
 'site': 453,
 'kill': 454,
 'robb': 455,
 'others': 456,
 'students': 457,
 'powerful': 458,
 'dozens': 459,
 'came': 460,
 'certain': 461,
 'described': 462,
 'documents': 463,
 'florida': 464,
 'secret': 465,
 'truth': 466,
 'six': 467,
 'd': 468,
 'republicans': 469,
 'earlier': 470,
 'protect': 471,
 'shooter': 472,
 'game': 473,
 'arizona': 474,
 'place': 475,
 'act': 476,
 'prison': 477,
 'pennsylvania': 478,
 'break': 479,
 'control': 480,
 'quarterback': 481,
 'nfl': 482,
 'amid': 483,
 'any': 484,
 'j': 485,
 'virus': 486,
 'sen': 487,
 'minister': 488,
 '2': 489,
 'much': 490,
 'tried': 491,
 'wanted': 492,
 '“this': 493,
 'allegedly': 494,
 'those': 495,
 'superstar': 496,
 'already': 497,
 'favorite': 498,
 'overturn': 499,
 'netflix': 500,
 'millions': 501,
 'congresswoman': 502,
 'good': 503,
 'victory': 504,
 'mariupol': 505,
 'zelenskyy': 506,
 'policy': 507,
 'fall': 508,
 'fled': 509,
 'put': 510,
 'viral': 511,
 'seen': 512,
 'dead': 513,
 'missing': 514,
 'behind': 515,
 'wave': 516,
 'claims': 517,
 'platform': 518,
 'trip': 519,
 'space': 520,
 'miles': 521,
 'michael': 522,
 'key': 523,
 'killing': 524,
 'different': 525,
 'mark': 526,
 'that’s': 527,
 'london': 528,
 'royal': 529,
 'cases': 530,
 '2022': 531,
 'watch': 532,
 'summer': 533,
 'workers': 534,
 'race': 535,
 'battle': 536,
 'book': 537,
 'hoping': 538,
 'icon': 539,
 'rapper': 540,
 'struck': 541,
 'united': 542,
 'nations': 543,
 'negotiations': 544,
 'r': 545,
 'best': 546,
 "they're": 547,
 'enforcement': 548,
 'democrats': 549,
 'state’s': 550,
 'using': 551,
 'every': 552,
 'final': 553,
 'slam': 554,
 'become': 555,
 'offensive': 556,
 'weather': 557,
 'testimony': 558,
 'award': 559,
 'arrested': 560,
 'use': 561,
 'step': 562,
 'flight': 563,
 'head': 564,
 'giant': 565,
 'laws': 566,
 'previously': 567,
 '24': 568,
 'leaving': 569,
 'wounded': 570,
 'followed': 571,
 'union': 572,
 'ever': 573,
 'big': 574,
 'sexual': 575,
 'beyond': 576,
 'going': 577,
 'adviser': 578,
 'release': 579,
 'think': 580,
 'voting': 581,
 'appeared': 582,
 'fbi': 583,
 'local': 584,
 'search': 585,
 'congressional': 586,
 'plan': 587,
 'hall': 588,
 'oil': 589,
 'officers': 590,
 'daughter': 591,
 'vice': 592,
 'candidate': 593,
 'critical': 594,
 'available': 595,
 'lot': 596,
 'recent': 597,
 'guns': 598,
 'whose': 599,
 'suspect': 600,
 'toward': 601,
 'album': 602,
 'suspended': 603,
 'john': 604,
 'appears': 605,
 'photo': 606,
 'wait': 607,
 'daily': 608,
 'strong': 609,
 'advice': 610,
 'streaming': 611,
 'jones': 612,
 'month': 613,
 'call': 614,
 'hold': 615,
 'gave': 616,
 'murder': 617,
 'saying': 618,
 'opened': 619,
 'community': 620,
 'k': 621,
 'once': 622,
 'stars': 623,
 'huffpost': 624,
 'through': 625,
 'won': 626,
 'party': 627,
 'academy': 628,
 'facing': 629,
 'filed': 630,
 'lgbtq': 631,
 'reveal': 632,
 'talk': 633,
 '20': 634,
 'volodymyr': 635,
 'border': 636,
 'demand': 637,
 'match': 638,
 'ordered': 639,
 'los': 640,
 'angeles': 641,
 'working': 642,
 'south': 643,
 "president's": 644,
 'visit': 645,
 'n': 646,
 'incident': 647,
 'activist': 648,
 'panel': 649,
 'breaking': 650,
 '7': 651,
 'kremlin': 652,
 'backed': 653,
 'kept': 654,
 'rain': 655,
 'knocked': 656,
 'annual': 657,
 'veteran': 658,
 'january': 659,
 'lady': 660,
 'robert': 661,
 'queen': 662,
 'left': 663,
 'organization': 664,
 'inside': 665,
 'ago': 666,
 'capital': 667,
 'scheduled': 668,
 'victim': 669,
 'chief': 670,
 'find': 671,
 'viewers': 672,
 'compared': 673,
 'well': 674,
 'mayor': 675,
 'tiktok': 676,
 'prices': 677,
 'rose': 678,
 'cancer': 679,
 "won't": 680,
 'training': 681,
 'plans': 682,
 'ways': 683,
 'documentary': 684,
 'age': 685,
 'remains': 686,
 'department': 687,
 'team': 688,
 'audience': 689,
 'finally': 690,
 'russia’s': 691,
 'heat': 692,
 'southern': 693,
 'performance': 694,
 'british': 695,
 'focus': 696,
 'countries': 697,
 'climate': 698,
 'claimed': 699,
 'tuesday': 700,
 'violent': 701,
 'states': 702,
 'congress': 703,
 'very': 704,
 'such': 705,
 'instagram': 706,
 "isn't": 707,
 'ceo': 708,
 'looks': 709,
 'gunman': 710,
 'supporters': 711,
 'flooding': 712,
 'unprecedented': 713,
 'survived': 714,
 'crash': 715,
 'counts': 716,
 'provide': 717,
 'jury': 718,
 'west': 719,
 'pushing': 720,
 'culture': 721,
 'classified': 722,
 'refused': 723,
 'private': 724,
 'thing': 725,
 'another': 726,
 'common': 727,
 'served': 728,
 'hbo': 729,
 'follow': 730,
 'present': 731,
 'along': 732,
 'message': 733,
 'operation': 734,
 'possible': 735,
 'term': 736,
 'having': 737,
 'job': 738,
 'decade': 739,
 'safety': 740,
 'offer': 741,
 'yet': 742,
 'paid': 743,
 'leave': 744,
 'musical': 745,
 '14': 746,
 'giving': 747,
 'michigan': 748,
 'fear': 749,
 'attorney': 750,
 'al': 751,
 'sentence': 752,
 'vaccine': 753,
 'endorsed': 754,
 'talks': 755,
 'coronavirus': 756,
 'monkeypox': 757,
 'ballot': 758,
 'living': 759,
 'cast': 760,
 'legislative': 761,
 'great': 762,
 'illinois': 763,
 'pitt': 764,
 'university': 765,
 'event': 766,
 'identified': 767,
 'funding': 768,
 'officer': 769,
 'attempt': 770,
 'street': 771,
 'employees': 772,
 'allowed': 773,
 'son': 774,
 'meeting': 775,
 'responded': 776,
 'opening': 777,
 'recently': 778,
 'upcoming': 779,
 'executive': 780,
 'coming': 781,
 'baby': 782,
 'criminal': 783,
 'share': 784,
 'presidential': 785,
 'didn’t': 786,
 'treatment': 787,
 'musician': 788,
 'cat': 789,
 'senior': 790,
 'far': 791,
 'then': 792,
 'nomination': 793,
 'hit': 794,
 'massacre': 795,
 'convicted': 796,
 'phone': 797,
 'fight': 798,
 'dr': 799,
 'continues': 800,
 'murdoch': 801,
 'riot': 802,
 'fears': 803,
 'kate': 804,
 'abortions': 805,
 'closed': 806,
 'little': 807,
 'mean': 808,
 'nominee': 809,
 'featured': 810,
 'emergency': 811,
 'shortly': 812,
 'trying': 813,
 'abbott': 814,
 'actually': 815,
 '21': 816,
 'events': 817,
 'means': 818,
 'strategy': 819,
 'animal': 820,
 'movement': 821,
 'isn’t': 822,
 'constitutional': 823,
 'king': 824,
 'march': 825,
 'immediately': 826,
 'less': 827,
 'goal': 828,
 'reporter': 829,
 'keep': 830,
 'nation’s': 831,
 'smith': 832,
 'candidates': 833,
 'hearing': 834,
 'concerns': 835,
 'you’re': 836,
 '25': 837,
 'ongoing': 838,
 'talking': 839,
 'supermarket': 840,
 'comments': 841,
 'oscars': 842,
 'plus': 843,
 'primary': 844,
 'absolutely': 845,
 'claim': 846,
 'mask': 847,
 'fighting': 848,
 'tax': 849,
 'civilians': 850,
 'doses': 851,
 'thursday': 852,
 'anchor': 853,
 'journalist': 854,
 'territory': 855,
 'european': 856,
 'soccer': 857,
 'underscores': 858,
 'growing': 859,
 'funeral': 860,
 'hurricane': 861,
 'later': 862,
 "man's": 863,
 'popular': 864,
 'saw': 865,
 'moscow': 866,
 'puerto': 867,
 'rico': 868,
 'hollywood': 869,
 'included': 870,
 'rise': 871,
 'floods': 872,
 'air': 873,
 'races': 874,
 'feel': 875,
 'among': 876,
 'entering': 877,
 "wasn't": 878,
 'towards': 879,
 'deadly': 880,
 'ground': 881,
 'repeatedly': 882,
 'mississippi': 883,
 'trail': 884,
 'writer': 885,
 'refugees': 886,
 'church': 887,
 'longest': 888,
 'staff': 889,
 'saved': 890,
 'oscar': 891,
 'winner': 892,
 'hours': 893,
 "she's": 894,
 'clearly': 895,
 'alexander': 896,
 'announcement': 897,
 'ambassador': 898,
 'television': 899,
 'harm': 900,
 'businesses': 901,
 'online': 902,
 'likely': 903,
 'blue': 904,
 'together': 905,
 'provided': 906,
 'atlanta': 907,
 'started': 908,
 'career': 909,
 'district': 910,
 'attention': 911,
 'confront': 912,
 'point': 913,
 'biggest': 914,
 'atomic': 915,
 'largest': 916,
 'network': 917,
 'code': 918,
 'additional': 919,
 'pulled': 920,
 'area': 921,
 'garden': 922,
 'b': 923,
 'international': 924,
 'guterres': 925,
 'responsibility': 926,
 'challenge': 927,
 'stabbing': 928,
 'choice': 929,
 'highest': 930,
 'block': 931,
 'makes': 932,
 '200': 933,
 'unemployment': 934,
 'austin': 935,
 'energy': 936,
 'agency': 937,
 'warned': 938,
 'council': 939,
 'threat': 940,
 'relief': 941,
 'notice': 942,
 'violations': 943,
 'data': 944,
 'privacy': 945,
 'heavy': 946,
 'threats': 947,
 'harassment': 948,
 'calls': 949,
 "doesn't": 950,
 'quipped': 951,
 "can't": 952,
 'fourth': 953,
 'clean': 954,
 'rains': 955,
 'mental': 956,
 'parts': 957,
 'areas': 958,
 'mtv': 959,
 'estate': 960,
 'small': 961,
 'artemis': 962,
 'each': 963,
 'deputy': 964,
 'unusually': 965,
 'reflects': 966,
 'soviet': 967,
 'foot': 968,
 'referred': 969,
 "you're": 970,
 'armed': 971,
 'raid': 972,
 'filing': 973,
 'hand': 974,
 'earned': 975,
 'though': 976,
 'pizza': 977,
 'steve': 978,
 'problem': 979,
 'here': 980,
 'launch': 981,
 'agent': 982,
 'october': 983,
 'moms': 984,
 'intense': 985,
 'lopez': 986,
 'supposed': 987,
 'cannot': 988,
 'graham': 989,
 'appearance': 990,
 'heard': 991,
 'jersey': 992,
 'posted': 993,
 'challenges': 994,
 'outside': 995,
 'marriage': 996,
 'details': 997,
 'allegations': 998,
 'hang': 999,
 'goofs': 1000,
 ...}

In [78]:
# Count of unique words in the dataset
# Add 1 because tokenizer indices start at 1, and 0 is reserved for padding
vocab_size=len(tokenizer.word_index) + 1

In [79]:
# Convert the short descriptions to sequences of integers
tokenizer.texts_to_sequences(data['short_description'])

[[131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36,
  639,
  8,
  2,
  508],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147,
  142,
  6,
  640,
  641],
 [413, 45, 30, 3, 287, 45, 203, 2148, 74, 75, 33, 2149],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157,
  2158,
  6,
  2159,
  2160],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241,
  252,
  2168,
  221,
  511],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148,
  22,
  514,
  167,
  13],
 [1243,
  10,
  515,
  45,
  19,
  853,
  8,
  26,
  2170,
  2171,
  222,
  854,
  1244,
  2172,
  15,
  65,
  1245,
  57,
  19,
  254],
 [38,
  61,
  414,
  3,
  101,
  41,
  2173,
  356,
  149,
  150,
  107,
  151,
  20,
  2,
  255,
  1246,
  2,
  34,
  36,
  855],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3,
  38,
  2179,
  2180,
  223],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205,
  7,
  63,
  1251,
  96],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224,
  64,
  1254,
  17,
  2,
  132,
  1255],
 [2,
  647,
  858,
  3,
  859,
  516,
  5,
  1256,
  64,
  2,
  860,
  8,
  2185,
  2186,
  25,
  11,
  40,
  5,
  2,
  170,
  2187,
  293,
  6,
  2188,
  2189,
  1257],
 [861,
  2190,
  1246,
  2,
  1258,
  7,
  1259,
  1260,
  7,
  11,
  2191,
  4,
  2192,
  358,
  2193,
  862,
  39,
  143],
 [40,
  863,
  517,
  10,
  24,
  2194,
  41,
  9,
  2,
  518,
  1261,
  257,
  864,
  2195,
  4,
  1262,
  3,
  2196,
  2197],
 [294,
  648,
  2198,
  1263,
  2,
  359,
  5,
  188,
  80,
  225,
  2199,
  1263,
  18,
  1264,
  4,
  2200,
  6,
  3,
  2201,
  254,
  14,
  2,
  55,
  649,
  226,
  2,
  259,
  154,
  415],
 [2202,
  360,
  650,
  519,
  4,
  2203,
  520,
  865,
  108,
  2204,
  1265,
  651,
  2205,
  227,
  7,
  1266,
  206,
  2206,
  101,
  521],
 [1267,
  2207,
  522,
  523,
  2208,
  2209,
  7,
  2210,
  2211,
  2,
  2212,
  81,
  416,
  2,
  2213,
  5,
  3,
  2214,
  355,
  1268,
  2215],
 [2216,
  2217,
  25,
  417,
  2,
  640,
  641,
  2218,
  418,
  107,
  132,
  123,
  1269,
  14,
  16,
  2219,
  2220,
  2221,
  18,
  295],
 [2,
  2222,
  7,
  2223,
  652,
  653,
  361,
  4,
  2224,
  57,
  296,
  2225,
  75,
  362,
  2,
  260,
  8,
  866,
  4,
  2226,
  2,
  96],
 [2,
  1258,
  7,
  1259,
  1260,
  144,
  2227,
  3,
  2228,
  15,
  2,
  2229,
  255,
  654,
  2230,
  2231,
  655,
  53,
  2,
  2232,
  1270,
  7,
  867,
  868],
 [8,
  2,
  358,
  261,
  363,
  869,
  18,
  2233,
  2234,
  2,
  2235,
  20,
  364,
  10,
  2,
  2236,
  2237,
  189,
  5,
  1271,
  115,
  1272,
  870,
  88,
  155,
  189],
 [35, 365, 2238, 15, 1273, 14, 2239, 871],
 [2,
  255,
  656,
  58,
  2,
  262,
  1274,
  7,
  2240,
  872,
  7,
  2241,
  6,
  867,
  868,
  145,
  2,
  297,
  13,
  2,
  1275,
  11,
  2242,
  32],
 [2,
  1276,
  2243,
  2244,
  11,
  2245,
  6,
  2,
  190,
  1277,
  873,
  874,
  9,
  146,
  50,
  23,
  2246,
  56,
  3,
  1278,
  524,
  2,
  1279,
  122,
  13],
 [19, 657, 2247, 298, 9, 3, 525, 875, 15, 299, 419, 2248, 56, 82, 2249],
 [526, 2250, 3, 2251, 658, 7, 1280, 2252, 11, 1281, 6, 1282, 6, 659, 300],
 [1283, 1284, 366, 76, 3, 1285, 1286, 2253, 44, 413, 146],
 [35,
  133,
  77,
  7,
  60,
  660,
  2254,
  77,
  47,
  876,
  367,
  5,
  2255,
  44,
  21,
  2256,
  7,
  2257,
  4,
  2258,
  7,
  132,
  293,
  44,
  4,
  1287,
  43,
  2259],
 [2,
  2260,
  357,
  13,
  2261,
  5,
  16,
  2262,
  263,
  28,
  171,
  2263,
  14,
  420,
  527,
  58,
  124,
  228,
  151],
 [2264,
  661,
  229,
  15,
  2,
  1288,
  2265,
  83,
  18,
  1289,
  2,
  2266,
  2267,
  7,
  2,
  2268,
  109,
  421],
 [34,
  36,
  35,
  133,
  77,
  6,
  528,
  8,
  2,
  860,
  5,
  662,
  2269,
  1290,
  89,
  16,
  1291,
  221,
  58,
  4,
  2,
  529,
  204,
  2270,
  2,
  2271,
  422,
  663,
  3,
  2272,
  2273,
  32],
 [368,
  877,
  423,
  301,
  43,
  207,
  878,
  2274,
  1292,
  7,
  6,
  86,
  530,
  2,
  2275,
  2276,
  369,
  2277,
  2,
  142,
  5,
  2278,
  264,
  148],
 [9, 290, 2, 2279, 60, 172, 2280, 5, 2281, 2282, 2283, 2284, 7, 2285, 2286],
 [2, 173, 46, 103, 208, 509, 56, 2, 2287, 6, 3, 424, 1293, 4, 2288, 67],
 [2289, 156, 90, 41, 27, 33, 2290, 4, 2, 1294, 531, 255, 15, 3, 2291, 255, 32],
 [867, 868, 11, 153, 3, 861, 532, 425, 15, 2, 255, 1295, 879, 2, 34, 36, 855],
 [2,
  132,
  131,
  664,
  12,
  2292,
  2,
  2293,
  31,
  3,
  2294,
  2295,
  6,
  2,
  1296,
  5,
  2,
  880,
  872,
  6,
  2296,
  39,
  533,
  15,
  1297,
  7,
  1298,
  534,
  9,
  2,
  881,
  535,
  4,
  536,
  2297,
  5,
  2298,
  7,
  97,
  2299],
 [2300,
  30,
  882,
  2301,
  10,
  2302,
  172,
  302,
  5,
  149,
  2303,
  426,
  207,
  44,
  51,
  527,
  91,
  9,
  2,
  1299,
  6,
  883],
 [2304,
  6,
  2,
  370,
  5,
  2,
  2305,
  2306,
  142,
  18,
  3,
  884,
  5,
  2307,
  303,
  230,
  4,
  2308,
  1300,
  32,
  2309,
  522,
  2310,
  59,
  2,
  157],
 [2,
  357,
  5,
  2,
  1301,
  2311,
  304,
  2312,
  3,
  885,
  5,
  2,
  1302,
  2313,
  8,
  2,
  2314,
  2315,
  6,
  2,
  2316,
  2317,
  2318],
 [104,
  2319,
  53,
  2,
  2320,
  34,
  36,
  2321,
  21,
  1282,
  1303,
  1304,
  168,
  8,
  2322,
  886],
 [2323,
  2324,
  2325,
  371,
  19,
  2326,
  7,
  18,
  2327,
  5,
  1305,
  665,
  22,
  1306,
  21,
  3,
  2328,
  2329,
  2330,
  2331,
  10,
  110,
  22,
  1307,
  7,
  107,
  97,
  155,
  2332,
  665,
  19,
  2333,
  887,
  2334,
  90,
  666],
 [3,
  1308,
  149,
  2335,
  18,
  54,
  2336,
  8,
  1309,
  667,
  7,
  2,
  109,
  27,
  265,
  2337,
  58,
  266,
  2338,
  149,
  9,
  425],
 [231,
  2339,
  5,
  2,
  2340,
  44,
  2341,
  888,
  427,
  81,
  44,
  12,
  668,
  4,
  1310,
  6,
  1311,
  2342,
  3,
  669,
  5,
  191,
  428,
  2343,
  6,
  1312,
  1313,
  6,
  26,
  105],
 [2,
  37,
  79,
  55,
  670,
  5,
  889,
  18,
  429,
  53,
  1314,
  15,
  174,
  5,
  3,
  134,
  305,
  56,
  2,
  259,
  154,
  175,
  372,
  9,
  2,
  176],
 [2,
  2344,
  115,
  1315,
  26,
  537,
  2345,
  11,
  1316,
  1317,
  227,
  44,
  413,
  65,
  221,
  1318,
  4,
  22,
  2346,
  8,
  168],
 [2347,
  1319,
  2348,
  4,
  2,
  1320,
  1321,
  7,
  232,
  177,
  22,
  2349,
  413,
  67,
  430,
  2350,
  39,
  878,
  2,
  60,
  125,
  1319,
  233,
  30,
  890,
  3,
  98],
 [2,
  891,
  892,
  13,
  65,
  1322,
  58,
  8,
  178,
  893,
  3,
  82,
  8,
  22,
  431,
  6,
  2,
  26,
  234,
  263],
 [2,
  373,
  71,
  59,
  374,
  2351,
  894,
  2352,
  58,
  1323,
  895,
  209,
  48,
  642,
  2353,
  2354,
  432],
 [2,
  1283,
  1284,
  2355,
  28,
  538,
  4,
  671,
  58,
  25,
  235,
  2,
  2356,
  539,
  2357,
  90,
  666],
 [2,
  1324,
  1325,
  540,
  2358,
  71,
  541,
  135,
  17,
  2,
  896,
  2359,
  116,
  6,
  2360,
  2361,
  4,
  179,
  2,
  897],
 [2362,
  2,
  37,
  34,
  36,
  898,
  4,
  2,
  542,
  543,
  7,
  3,
  2363,
  2364,
  6,
  2365,
  544,
  232,
  2366,
  14,
  68,
  293],
 [2, 899, 306, 307, 371, 2367, 180, 308, 101, 672, 673, 4, 63, 175, 375],
 [79,
  55,
  376,
  267,
  2368,
  2369,
  2370,
  13,
  3,
  2371,
  2372,
  12,
  48,
  2373,
  7,
  166,
  900,
  1326,
  15,
  674,
  15,
  901],
 [2,
  1327,
  264,
  2374,
  12,
  2375,
  4,
  433,
  37,
  2376,
  675,
  2377,
  2378,
  545,
  6,
  2,
  264,
  126],
 [3,
  34,
  36,
  1239,
  10,
  2379,
  423,
  902,
  517,
  364,
  10,
  2380,
  8,
  301,
  31,
  1328,
  181,
  2381,
  9,
  676,
  28,
  903,
  4,
  2382,
  57,
  1329,
  2383,
  14,
  1330],
 [9, 3, 2384, 2385, 677, 678, 1331, 180, 20, 3, 2386, 2387, 6, 309],
 [2, 357, 11, 546, 229, 8, 2, 1332, 263, 2388],
 [547,
  1333,
  8,
  2389,
  2390,
  52,
  69,
  27,
  236,
  1334,
  2391,
  158,
  29,
  2392,
  2393,
  2394,
  10,
  30,
  1335,
  6,
  2,
  428],
 [679,
  377,
  48,
  2395,
  378,
  7,
  904,
  2,
  35,
  13,
  290,
  1336,
  679,
  12,
  310,
  159,
  99,
  379,
  905],
 [25,
  159,
  30,
  9,
  2,
  1278,
  12,
  25,
  2396,
  1337,
  434,
  32,
  1338,
  59,
  192,
  181,
  146],
 [2,
  2397,
  1339,
  69,
  2398,
  2399,
  680,
  30,
  4,
  2400,
  14,
  2,
  1340,
  66,
  1341,
  2401,
  7,
  906,
  1342,
  227,
  4,
  2402,
  43,
  681],
 [2403, 2404, 1343, 14, 2, 907, 2405, 7, 908, 16, 160, 548, 909, 6, 1344],
 [549,
  6,
  2,
  550,
  38,
  2406,
  55,
  910,
  28,
  2407,
  25,
  27,
  210,
  9,
  3,
  864,
  104,
  37,
  675],
 [77,
  682,
  4,
  2408,
  911,
  4,
  3,
  26,
  2409,
  653,
  1345,
  10,
  2410,
  4,
  2411,
  551,
  2412,
  2413,
  4,
  1346,
  64,
  435,
  2414],
 [2,
  1347,
  436,
  1348,
  18,
  289,
  2415,
  683,
  4,
  912,
  2416,
  31,
  1349,
  2417,
  2418,
  7,
  1350,
  6,
  22,
  2419],
 [437,
  48,
  31,
  2420,
  66,
  136,
  2421,
  2,
  2422,
  5,
  2423,
  2424,
  1351,
  2,
  26,
  684,
  1352,
  16,
  2425,
  44,
  552,
  2426,
  5,
  23],
 [2427,
  2428,
  1353,
  2429,
  2430,
  6,
  2,
  34,
  36,
  1354,
  553,
  4,
  2431,
  16,
  60,
  311,
  554,
  17,
  685,
  173,
  7,
  555,
  2,
  2432,
  83,
  4,
  380,
  57,
  4,
  88,
  180,
  6,
  2,
  2433],
 [1355,
  117,
  1356,
  64,
  3,
  1357,
  1358,
  312,
  1359,
  10,
  11,
  171,
  859,
  7,
  438,
  367,
  5,
  2434,
  381],
 [35,
  133,
  77,
  18,
  1360,
  2,
  1361,
  2435,
  5,
  2,
  1362,
  1363,
  439,
  382,
  174,
  6,
  3,
  2436,
  2437,
  2438,
  307,
  232,
  17,
  2,
  2439,
  153,
  3,
  2440,
  655],
 [1294,
  2441,
  686,
  3,
  913,
  8,
  2442,
  9,
  2,
  2443,
  439,
  2444,
  190,
  313,
  2445,
  1304,
  3,
  34,
  36,
  2446,
  9,
  2447,
  1364],
 [2,
  2448,
  40,
  5,
  2,
  156,
  914,
  915,
  262,
  2449,
  6,
  2,
  132,
  18,
  54,
  2450,
  29,
  68,
  314,
  111,
  355,
  6,
  2,
  96,
  84,
  1360,
  63,
  2451,
  82,
  9,
  146],
 [2452,
  2453,
  12,
  440,
  15,
  2,
  916,
  2454,
  917,
  7,
  27,
  903,
  1365,
  1252,
  8,
  2455,
  7,
  115,
  2456,
  4,
  2457,
  2,
  918,
  15,
  674],
 [2,
  225,
  687,
  1366,
  42,
  1367,
  2458,
  8,
  2,
  431,
  1368,
  688,
  1366,
  3,
  1367,
  211,
  7,
  3,
  2459],
 [2,
  357,
  59,
  2,
  689,
  24,
  11,
  2460,
  2461,
  4,
  33,
  690,
  2462,
  57,
  263,
  42,
  44,
  15,
  24,
  18,
  107,
  919,
  2463,
  6,
  2,
  2464],
 [691,
  268,
  1369,
  237,
  10,
  1370,
  27,
  33,
  920,
  141,
  6,
  42,
  921,
  145,
  3,
  161,
  2465,
  556,
  18,
  117,
  440,
  2466],
 [20,
  3,
  156,
  82,
  692,
  516,
  10,
  206,
  2467,
  2,
  2468,
  1274,
  693,
  312,
  441,
  1371,
  557,
  51,
  72,
  3,
  1372,
  1373,
  255],
 [161, 314, 28, 2469, 26, 2470, 6, 43, 2471, 64, 68, 314, 6, 2, 1374],
 [1375,
  2472,
  238,
  6,
  3,
  1376,
  5,
  1377,
  8,
  1378,
  90,
  5,
  150,
  32,
  2,
  315,
  71,
  59,
  2,
  442,
  20,
  24,
  2473,
  16,
  2474,
  2475,
  922,
  694],
 [2476, 2477, 558, 75, 33, 3, 193, 1379, 4, 2, 545, 923, 2478, 443, 5, 2479],
 [383, 695, 7, 924, 2480, 1380, 2, 2481, 5, 2, 34, 2482, 36, 888, 2483, 2484],
 [2,
  173,
  46,
  103,
  269,
  2485,
  7,
  2486,
  539,
  27,
  2487,
  2,
  531,
  2488,
  559,
  8,
  22,
  696,
  9,
  384,
  2489,
  361],
 [1381,
  21,
  2490,
  2491,
  925,
  13,
  697,
  1382,
  38,
  926,
  8,
  698,
  316,
  137,
  30,
  1383,
  39,
  927],
 [1384,
  444,
  172,
  2492,
  661,
  2493,
  11,
  560,
  6,
  2,
  2494,
  928,
  5,
  2495,
  2496,
  25,
  76,
  54,
  226,
  16,
  142],
 [2, 1385, 2497, 6, 2498, 53, 2, 37, 60, 2499, 2500, 929, 8, 2, 2501, 82],
 [2,
  87,
  13,
  24,
  11,
  118,
  2502,
  2503,
  194,
  162,
  2,
  123,
  2504,
  10,
  24,
  2505,
  8,
  16,
  98,
  7,
  11,
  1386,
  1387,
  2,
  2506,
  194,
  2507],
 [2508,
  5,
  2,
  2509,
  699,
  2510,
  117,
  2,
  1342,
  2511,
  2512,
  51,
  2,
  1327,
  930,
  80,
  1316,
  10,
  2513],
 [2,
  445,
  89,
  1388,
  2514,
  2515,
  2516,
  4,
  931,
  100,
  2517,
  932,
  23,
  1389,
  8,
  41,
  551,
  2518,
  2519,
  66,
  2520,
  4,
  561,
  195],
 [2,
  182,
  6,
  2521,
  19,
  100,
  446,
  196,
  700,
  7,
  1390,
  383,
  534,
  7,
  2522,
  665,
  2,
  1391,
  223,
  1392],
 [2,
  2523,
  1393,
  1394,
  27,
  690,
  33,
  3,
  385,
  5,
  2,
  2524,
  2525,
  2526,
  14,
  2527,
  97,
  2528,
  239,
  2529],
 [6,
  170,
  5,
  2,
  933,
  2530,
  183,
  10,
  1395,
  2531,
  1396,
  2532,
  47,
  2533,
  701,
  2534,
  66,
  2535,
  44,
  112,
  52,
  2536,
  17,
  92],
 [702,
  28,
  2537,
  141,
  7,
  703,
  12,
  1397,
  4,
  562,
  6,
  136,
  20,
  2,
  428,
  1398,
  2,
  934,
  2538,
  2539],
 [1399,
  122,
  6,
  935,
  163,
  69,
  19,
  355,
  1400,
  262,
  2540,
  12,
  2541,
  563,
  2542,
  136,
  15,
  2543,
  18,
  54,
  2544],
 [2,
  564,
  5,
  2,
  924,
  915,
  936,
  937,
  938,
  2,
  34,
  646,
  313,
  939,
  10,
  2545,
  704,
  704,
  2546,
  75,
  210,
  2547,
  17,
  2548],
 [705,
  439,
  30,
  555,
  3,
  859,
  940,
  4,
  34,
  36,
  386,
  14,
  257,
  317,
  1401,
  1402,
  148,
  111,
  73,
  46],
 [3, 212, 182, 110, 42, 41, 6, 1358, 312, 39, 270],
 [2,
  1403,
  2549,
  2550,
  2551,
  2552,
  441,
  2553,
  56,
  941,
  1404,
  2554,
  6,
  3,
  156,
  1331,
  1405,
  4,
  2,
  2555],
 [2, 100, 686, 153, 3, 1308, 149, 942, 84, 60, 221, 56, 1406, 9, 309, 447],
 [2,
  138,
  157,
  565,
  11,
  2556,
  8,
  943,
  5,
  944,
  945,
  566,
  448,
  4,
  301,
  31,
  135,
  9,
  706],
 [124,
  12,
  26,
  317,
  2557,
  449,
  2,
  163,
  2558,
  172,
  386,
  10,
  171,
  707,
  1245,
  7,
  3,
  946,
  67,
  2559,
  10,
  119,
  1326,
  203,
  2560],
 [2,
  2561,
  450,
  20,
  2,
  77,
  302,
  1407,
  10,
  2,
  68,
  1408,
  6,
  1409,
  298,
  1410,
  5,
  2562,
  2563,
  2564,
  8,
  561,
  6,
  78],
 [2, 15, 23, 11, 269, 13, 24, 72, 426, 387, 119, 2565, 451, 152, 7, 2566],
 [2567,
  2568,
  13,
  1330,
  2569,
  2,
  1411,
  8,
  919,
  947,
  948,
  7,
  136,
  271,
  9,
  126,
  82],
 [2570, 708, 1412, 452, 76, 567, 1413, 949, 4, 931, 2, 453],
 [388,
  2571,
  6,
  114,
  2572,
  15,
  272,
  15,
  24,
  950,
  454,
  238,
  66,
  114,
  204,
  2,
  2573,
  951],
 [50,
  2574,
  2575,
  709,
  17,
  2,
  2576,
  10,
  2577,
  177,
  22,
  2578,
  65,
  952,
  236,
  1414,
  233,
  568,
  50,
  3,
  710,
  2579,
  22,
  953,
  1415,
  1416,
  17,
  455,
  318,
  6,
  319,
  163,
  524,
  173,
  135,
  7,
  42,
  389,
  7,
  569,
  22,
  7,
  456,
  570],
 [2580,
  2581,
  949,
  9,
  711,
  4,
  320,
  20,
  157,
  321,
  2582,
  1417,
  2583,
  223,
  1418,
  2584,
  1419,
  4,
  384,
  93,
  1420],
 [67,
  6,
  1421,
  69,
  19,
  1422,
  18,
  54,
  117,
  6,
  2,
  2585,
  5,
  3,
  253,
  25,
  11,
  2586,
  194,
  2587],
 [390,
  5,
  1309,
  1423,
  155,
  667,
  171,
  203,
  30,
  954,
  149,
  20,
  955,
  1335,
  2,
  1424,
  1425],
 [167,
  1426,
  10,
  38,
  712,
  12,
  391,
  15,
  1427,
  2588,
  2589,
  21,
  713,
  1428,
  955,
  10,
  30,
  110,
  206,
  180,
  1429,
  41],
 [457,
  25,
  714,
  2,
  233,
  568,
  162,
  17,
  455,
  318,
  6,
  163,
  28,
  2590,
  2,
  533,
  14,
  3,
  127,
  5,
  956,
  131,
  365,
  273,
  2591],
 [1430,
  7,
  946,
  655,
  2592,
  957,
  5,
  2593,
  197,
  9,
  146,
  2594,
  2595,
  712,
  7,
  1431,
  317,
  2596,
  6,
  86,
  958],
 [2597,
  322,
  1414,
  2,
  2598,
  959,
  373,
  123,
  21,
  2,
  355,
  1268,
  2,
  1432,
  123,
  27,
  33,
  2599,
  17,
  2,
  2600,
  2601,
  2602,
  960,
  6,
  1433],
 [3,
  1279,
  18,
  54,
  560,
  20,
  2603,
  3,
  961,
  2604,
  53,
  1434,
  883,
  194,
  438,
  4,
  715,
  56,
  3,
  1435,
  1242],
 [174, 5, 2, 520, 2605, 962, 375, 2, 1436, 12, 2, 170, 458, 4, 2606],
 [2607, 1437, 571, 2608, 2609, 29, 1438, 459, 13, 122],
 [2610,
  67,
  323,
  2611,
  2612,
  2613,
  14,
  107,
  2614,
  716,
  5,
  2615,
  5,
  945,
  24,
  75,
  433,
  57,
  4,
  40,
  46,
  6,
  2616,
  8,
  963,
  1439],
 [2617,
  37,
  964,
  2618,
  2619,
  12,
  72,
  208,
  668,
  4,
  717,
  558,
  4,
  2,
  311,
  718,
  9,
  213],
 [2,
  255,
  44,
  2,
  60,
  861,
  5,
  19,
  965,
  2620,
  255,
  392,
  44,
  12,
  2621,
  31,
  2622,
  521,
  719,
  5,
  2,
  2623],
 [2,
  1440,
  523,
  860,
  966,
  2,
  2624,
  2625,
  31,
  2,
  2626,
  5,
  2627,
  25,
  12,
  2628,
  29,
  119,
  17,
  184,
  8,
  2,
  2629,
  5,
  2,
  967,
  572],
 [2,
  1441,
  563,
  5,
  2,
  2630,
  968,
  962,
  62,
  1436,
  44,
  2,
  170,
  458,
  573,
  2631,
  29,
  2632,
  44,
  11,
  2633,
  196,
  6,
  2,
  2634,
  290],
 [2,
  934,
  2635,
  678,
  4,
  274,
  651,
  21,
  3,
  414,
  1442,
  1440,
  5,
  274,
  308,
  6,
  309,
  15,
  38,
  393,
  460,
  128,
  2,
  2636,
  4,
  324,
  8,
  1443],
 [2637,
  2638,
  76,
  969,
  4,
  325,
  326,
  394,
  7,
  1444,
  2639,
  918,
  84,
  2640,
  19,
  1445,
  327,
  15,
  19,
  2641,
  50,
  65,
  11,
  60,
  1446,
  8,
  551,
  2,
  2642],
 [112,
  94,
  1447,
  12,
  2643,
  66,
  970,
  2644,
  5,
  2645,
  449,
  1448,
  2646,
  7,
  1449,
  5,
  2647,
  1450,
  39,
  2648,
  75,
  33,
  8,
  45],
 [2,
  2649,
  11,
  232,
  29,
  2650,
  8,
  206,
  178,
  363,
  321,
  19,
  971,
  972,
  5,
  22,
  2651,
  2652,
  184],
 [2, 2653, 183, 3, 2654, 83, 1386, 3, 2655],
 [2,
  713,
  378,
  1451,
  12,
  2656,
  3,
  2657,
  2658,
  10,
  233,
  164,
  1452,
  85,
  2,
  2659,
  692,
  516],
 [2,
  2660,
  62,
  1453,
  45,
  2661,
  1348,
  966,
  9,
  720,
  64,
  3,
  721,
  145,
  1349,
  269,
  2662,
  47,
  391,
  4,
  1454,
  3,
  461,
  2663,
  4,
  179,
  23,
  574],
 [2,
  2664,
  2665,
  973,
  462,
  70,
  49,
  7,
  16,
  1455,
  328,
  48,
  974,
  53,
  722,
  2666,
  17,
  2,
  1456],
 [2,
  967,
  2667,
  73,
  395,
  208,
  975,
  206,
  180,
  101,
  136,
  976,
  24,
  723,
  4,
  2668,
  2,
  977,
  9,
  1457],
 [2,
  95,
  12,
  2669,
  4,
  2670,
  2671,
  6,
  268,
  5,
  106,
  49,
  368,
  26,
  301,
  2672,
  4,
  722,
  463,
  232,
  17,
  16,
  464,
  960],
 [228,
  28,
  2,
  914,
  2673,
  6,
  2,
  132,
  978,
  1458,
  13,
  6,
  329,
  4,
  2,
  275,
  35,
  1459,
  330,
  465,
  463,
  17,
  16,
  724,
  2674],
 [2675,
  2676,
  43,
  240,
  64,
  2,
  269,
  25,
  1460,
  121,
  5,
  2677,
  327,
  575,
  2678,
  2679,
  6,
  16,
  241,
  396],
 [209, 40, 725, 20, 726, 8, 106, 139, 979, 2680, 466, 138],
 [576, 2681, 124, 28, 97, 727, 378, 1461, 10, 970, 1462, 14, 1463, 1237, 2682],
 [2683,
  577,
  4,
  434,
  92,
  1464,
  2684,
  980,
  32,
  2,
  962,
  1465,
  1466,
  13,
  20,
  2,
  60,
  981,
  11,
  2685],
 [2686,
  25,
  17,
  40,
  913,
  728,
  15,
  3,
  79,
  55,
  331,
  578,
  12,
  13,
  4,
  30,
  2687,
  49,
  2688,
  17,
  3,
  465,
  150,
  982,
  85,
  2,
  176,
  129],
 [729,
  27,
  579,
  3,
  467,
  174,
  730,
  57,
  4,
  2,
  123,
  1467,
  6,
  983,
  31,
  2,
  2689,
  397,
  2690,
  303,
  29,
  1468,
  2691],
 [984,
  14,
  2692,
  1450,
  2693,
  2694,
  468,
  2695,
  875,
  19,
  985,
  51,
  1469,
  516,
  5,
  2696,
  1470,
  66,
  97,
  2697,
  2698,
  165,
  2699,
  7,
  209,
  38,
  727,
  61,
  45,
  322,
  580],
 [2,
  676,
  1471,
  2700,
  2701,
  2702,
  7,
  2,
  2703,
  540,
  117,
  43,
  2704,
  172,
  44,
  51,
  22,
  275,
  2705,
  986,
  12,
  48,
  2706,
  31,
  23],
 [55,
  189,
  28,
  113,
  987,
  4,
  561,
  2707,
  581,
  50,
  52,
  988,
  33,
  731,
  332,
  4,
  276,
  173,
  51,
  1472,
  48,
  2708,
  1455,
  21,
  581,
  1473,
  9,
  2,
  224,
  884],
 [2709,
  469,
  273,
  238,
  1474,
  50,
  23,
  450,
  4,
  49,
  124,
  12,
  88,
  160,
  989,
  13,
  9,
  192,

In [80]:
input_sequences = []
for line in data['short_description']:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [81]:
input_sequences

[[131, 249],
 [131, 249, 13],
 [131, 249, 13, 23],
 [131, 249, 13, 23, 12],
 [131, 249, 13, 23, 12, 286],
 [131, 249, 13, 23, 12, 286, 355],
 [131, 249, 13, 23, 12, 286, 355, 4],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637, 166],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637, 166, 638],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637, 166, 638, 57],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637, 166, 638, 57, 14],
 [131, 249, 13, 23, 12, 286, 355, 4, 2139, 250, 637, 166, 638, 57, 14, 2],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36,
  639],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36,
  639,
  8],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36,
  639,
  8,
  2],
 [131,
  249,
  13,
  23,
  12,
  286,
  355,
  4,
  2139,
  250,
  637,
  166,
  638,
  57,
  14,
  2,
  2140,
  101,
  851,
  5,
  2,
  26,
  2141,
  2,
  34,
  36,
  639,
  8,
  2,
  508],
 [24, 11],
 [24, 11, 2142],
 [24, 11, 2142, 29],
 [24, 11, 2142, 29, 2143],
 [24, 11, 2142, 29, 2143, 7],
 [24, 11, 2142, 29, 2143, 7, 2144],
 [24, 11, 2142, 29, 2143, 7, 2144, 50],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141, 5],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141, 5, 2],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141, 5, 2, 2145],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141, 5, 2, 2145, 20],
 [24, 11, 2142, 29, 2143, 7, 2144, 50, 24, 509, 4, 2, 141, 5, 2, 2145, 20, 2],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147,
  142],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147,
  142,
  6],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147,
  142,
  6,
  640],
 [24,
  11,
  2142,
  29,
  2143,
  7,
  2144,
  50,
  24,
  509,
  4,
  2,
  141,
  5,
  2,
  2145,
  20,
  2,
  2146,
  220,
  4,
  2,
  34,
  36,
  2147,
  142,
  6,
  640,
  641],
 [413, 45],
 [413, 45, 30],
 [413, 45, 30, 3],
 [413, 45, 30, 3, 287],
 [413, 45, 30, 3, 287, 45],
 [413, 45, 30, 3, 287, 45, 203],
 [413, 45, 30, 3, 287, 45, 203, 2148],
 [413, 45, 30, 3, 287, 45, 203, 2148, 74],
 [413, 45, 30, 3, 287, 45, 203, 2148, 74, 75],
 [413, 45, 30, 3, 287, 45, 203, 2148, 74, 75, 33],
 [413, 45, 30, 3, 287, 45, 203, 2148, 74, 75, 33, 2149],
 [2150, 510],
 [2150, 510, 2151],
 [2150, 510, 2151, 57],
 [2150, 510, 2151, 57, 2152],
 [2150, 510, 2151, 57, 2152, 9],
 [2150, 510, 2151, 57, 2152, 9, 114],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7, 24],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7, 24, 2155],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7, 24, 2155, 102],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7, 24, 2155, 102, 62],
 [2150, 510, 2151, 57, 2152, 9, 114, 2153, 2154, 7, 24, 2155, 102, 62, 11],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157,
  2158],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157,
  2158,
  6],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157,
  2158,
  6,
  2159],
 [2150,
  510,
  2151,
  57,
  2152,
  9,
  114,
  2153,
  2154,
  7,
  24,
  2155,
  102,
  62,
  11,
  2156,
  16,
  1237,
  14,
  3,
  288,
  2157,
  2158,
  6,
  2159,
  2160],
 [1238, 2161],
 [1238, 2161, 121],
 [1238, 2161, 121, 2162],
 [1238, 2161, 121, 2162, 1239],
 [1238, 2161, 121, 2162, 1239, 2163],
 [1238, 2161, 121, 2162, 1239, 2163, 2164],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166, 22],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166, 22, 7],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166, 22, 7, 2167],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166, 22, 7, 2167, 22],
 [1238, 2161, 121, 2162, 1239, 2163, 2164, 5, 2165, 2166, 22, 7, 2167, 22, 3],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241,
  252],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241,
  252,
  2168],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241,
  252,
  2168,
  221],
 [1238,
  2161,
  121,
  2162,
  1239,
  2163,
  2164,
  5,
  2165,
  2166,
  22,
  7,
  2167,
  22,
  3,
  1240,
  20,
  251,
  5,
  2,
  1241,
  252,
  2168,
  221,
  511],
 [2, 2169],
 [2, 2169, 46],
 [2, 2169, 46, 103],
 [2, 2169, 46, 103, 253],
 [2, 2169, 46, 103, 253, 11],
 [2, 2169, 46, 103, 253, 11, 512],
 [2, 2169, 46, 103, 253, 11, 512, 642],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288, 1242],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288, 1242, 9],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288, 1242, 9, 852],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288, 1242, 9, 852, 65],
 [2, 2169, 46, 103, 253, 11, 512, 642, 17, 2, 643, 288, 1242, 9, 852, 65, 11],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148,
  22],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148,
  22,
  514],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148,
  22,
  514,
  167],
 [2,
  2169,
  46,
  103,
  253,
  11,
  512,
  642,
  17,
  2,
  643,
  288,
  1242,
  9,
  852,
  65,
  11,
  289,
  513,
  290,
  20,
  22,
  204,
  148,
  22,
  514,
  167,
  13],
 [1243, 10],
 [1243, 10, 515],
 [1243, 10, 515, 45],
 [1243, 10, 515, 45, 19],
 [1243, 10, 515, 45, 19, 853],
 [1243, 10, 515, 45, 19, 853, 8],
 [1243, 10, 515, 45, 19, 853, 8, 26],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222, 854],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222, 854, 1244],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222, 854, 1244, 2172],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222, 854, 1244, 2172, 15],
 [1243, 10, 515, 45, 19, 853, 8, 26, 2170, 2171, 222, 854, 1244, 2172, 15, 65],
 [1243,
  10,
  515,
  45,
  19,
  853,
  8,
  26,
  2170,
  2171,
  222,
  854,
  1244,
  2172,
  15,
  65,
  1245],
 [1243,
  10,
  515,
  45,
  19,
  853,
  8,
  26,
  2170,
  2171,
  222,
  854,
  1244,
  2172,
  15,
  65,
  1245,
  57],
 [1243,
  10,
  515,
  45,
  19,
  853,
  8,
  26,
  2170,
  2171,
  222,
  854,
  1244,
  2172,
  15,
  65,
  1245,
  57,
  19],
 [1243,
  10,
  515,
  45,
  19,
  853,
  8,
  26,
  2170,
  2171,
  222,
  854,
  1244,
  2172,
  15,
  65,
  1245,
  57,
  19,
  254],
 [38, 61],
 [38, 61, 414],
 [38, 61, 414, 3],
 [38, 61, 414, 3, 101],
 [38, 61, 414, 3, 101, 41],
 [38, 61, 414, 3, 101, 41, 2173],
 [38, 61, 414, 3, 101, 41, 2173, 356],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151, 20],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151, 20, 2],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151, 20, 2, 255],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151, 20, 2, 255, 1246],
 [38, 61, 414, 3, 101, 41, 2173, 356, 149, 150, 107, 151, 20, 2, 255, 1246, 2],
 [38,
  61,
  414,
  3,
  101,
  41,
  2173,
  356,
  149,
  150,
  107,
  151,
  20,
  2,
  255,
  1246,
  2,
  34],
 [38,
  61,
  414,
  3,
  101,
  41,
  2173,
  356,
  149,
  150,
  107,
  151,
  20,
  2,
  255,
  1246,
  2,
  34,
  36],
 [38,
  61,
  414,
  3,
  101,
  41,
  2173,
  356,
  149,
  150,
  107,
  151,
  20,
  2,
  255,
  1246,
  2,
  34,
  36,
  855],
 [6, 2174],
 [6, 2174, 357],
 [6, 2174, 357, 2175],
 [6, 2174, 357, 2175, 2176],
 [6, 2174, 357, 2175, 2176, 2177],
 [6, 2174, 357, 2175, 2176, 2177, 152],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247, 5],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247, 5, 1248],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247, 5, 1248, 7],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247, 5, 1248, 7, 1249],
 [6, 2174, 357, 2175, 2176, 2177, 152, 2178, 14, 2, 1247, 5, 1248, 7, 1249, 4],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3,
  38],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3,
  38,
  2179],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3,
  38,
  2179,
  2180],
 [6,
  2174,
  357,
  2175,
  2176,
  2177,
  152,
  2178,
  14,
  2,
  1247,
  5,
  1248,
  7,
  1249,
  4,
  256,
  3,
  38,
  2179,
  2180,
  223],
 [79, 55],
 [79, 55, 122],
 [79, 55, 122, 69],
 [79, 55, 122, 69, 2],
 [79, 55, 122, 69, 2, 2181],
 [79, 55, 122, 69, 2, 2181, 5],
 [79, 55, 122, 69, 2, 2181, 5, 2],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646, 39],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646, 39, 46],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646, 39, 46, 27],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646, 39, 46, 27, 33],
 [79, 55, 122, 69, 2, 2181, 5, 2, 644, 645, 4, 2, 34, 646, 39, 46, 27, 33, 3],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205,
  7],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205,
  7,
  63],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205,
  7,
  63,
  1251],
 [79,
  55,
  122,
  69,
  2,
  2181,
  5,
  2,
  644,
  645,
  4,
  2,
  34,
  646,
  39,
  46,
  27,
  33,
  3,
  291,
  2182,
  1250,
  5,
  205,
  7,
  63,
  1251,
  96],
 [2183, 18],
 [2183, 18, 292],
 [2183, 18, 292, 153],
 [2183, 18, 292, 153, 1252],
 [2183, 18, 292, 153, 1252, 21],
 [2183, 18, 292, 153, 1252, 21, 257],
 [2183, 18, 292, 153, 1252, 21, 257, 856],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25, 258],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25, 258, 4],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25, 258, 4, 168],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25, 258, 4, 168, 3],
 [2183, 18, 292, 153, 1252, 21, 257, 856, 857, 2184, 25, 258, 4, 168, 3, 1253],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224,
  64],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224,
  64,
  1254],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224,
  64,
  1254,
  17],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,
  168,
  3,
  1253,
  169,
  224,
  64,
  1254,
  17,
  2],
 [2183,
  18,
  292,
  153,
  1252,
  21,
  257,
  856,
  857,
  2184,
  25,
  258,
  4,

In [82]:
max_len = max(len(x) for x in input_sequences)

In [83]:
max_len

44

In [84]:
input = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [85]:
# All row 
X = input[:,:-1]
# Final word of each row
y = np.array(input[:,-1])

### Train Test split

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
X_train.shape, y_train.shape

((15442, 43), (15442,))

In [88]:
max_len = X.shape[1]

### Create a model

In [89]:
model = Sequential([
    Embedding(vocab_size, 128, input_length=max_len),
    LSTM(256),
    Dense(vocab_size, activation='softmax')
])

/home/linux/Desktop/projects/demos/next-word-prediction-using-lstm/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [90]:
model.compile(
    loss='sparse_categorical_crossentropy', 
    optimizer='adam', 
    metrics=['accuracy']
    )

In [91]:
model.build(input_shape=(None, max_len))

In [92]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 43, 128)        │       724,608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5661)           │     1,454,877 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,573,725 (9.82 MB)

 Trainable params: 2,573,725 (9.82 MB)

 Non-trainable params: 0 (0.00 B)

In [93]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 70s 139ms/step - accuracy: 0.0547 - loss: 7.5819 - val_accuracy: 0.0601 - val_loss: 7.4644
Epoch 2/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 61s 126ms/step - accuracy: 0.0639 - loss: 6.9455 - val_accuracy: 0.0666 - val_loss: 7.5735
Epoch 3/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 70s 144ms/step - accuracy: 0.0757 - loss: 6.5949 - val_accuracy: 0.0717 - val_loss: 7.6952
Epoch 4/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 76s 131ms/step - accuracy: 0.0873 - loss: 6.2240 - val_accuracy: 0.0746 - val_loss: 7.8574
Epoch 5/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 66s 136ms/step - accuracy: 0.1005 - loss: 5.7358 - val_accuracy: 0.0730 - val_loss: 8.0954
Epoch 6/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 208s 431ms/step - accuracy: 0.1212 - loss: 5.1438 - val_accuracy: 0.0717 - val_loss: 8.3568
Epoch 7/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 65s 135ms/step - accuracy: 0.1574 - loss: 4.5079 - val_accuracy: 0.0697 - val_loss: 8.6422
Epoch 8/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 199s 157ms/step - accuracy: 0.2384 - loss: 3.8876 - val_accuracy: 0.0681 - val_loss: 8.9046
Epoch 9/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 73s 151ms/step - accuracy: 0.3503 - loss: 3.3027 - val_accuracy: 0.0642 - val_loss: 9.1543
Epoch 10/10
483/483 ━━━━━━━━━━━━━━━━━━━━ 64s 132ms/step - accuracy: 0.4628 - loss: 2.7646 - val_accuracy: 0.0624 - val_loss: 9.3776

In [94]:
model.save('nextword.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [95]:
with open('tokenzier.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)