In [1]:
# Dataset: https://www.kaggle.com/datasets/rmisra/news-category-dataset

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense 
from sklearn.model_selection import train_test_split
import pickle

### Date gathering

In [3]:
data = pd.read_json('News_Category_Dataset_v3.json', lines=True)

### Data exploration

In [4]:
data

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [5]:
data.shape

(209527, 6)

In [6]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [7]:
# We need only the short description for our next word prediction task. So we will drop the other columns.
data = data[['short_description']]

In [8]:
data

                                        short_description
0       Health experts said it is too early to predict...
1       He was subdued by passengers and crew when he ...
2       "Until you have a dog you don't understand wha...
3       "Accidentally put grown-up toothpaste on my to...
4       Amy Cooper accused investment firm Franklin Te...
...                                                   ...
209522  Verizon Wireless and AT&T are already promotin...
209523  Afterward, Azarenka, more effusive with the pr...
209524  Leading up to Super Bowl XLVI, the most talked...
209525  CORRECTION: An earlier version of this story i...
209526  The five-time all-star center tore into his te...

[209527 rows x 1 columns]

### Check null and duplicate columns and remove it

In [9]:
# Check null values
data.isnull().sum()

short_description    0
dtype: int64

In [10]:
# Check duplicates
data.duplicated().sum()

np.int64(22505)

In [11]:
# Drop duplicates
data.drop_duplicates(inplace=True)

In [12]:
# Check duplicates after remove it
data.duplicated().sum()

np.int64(0)

### Date preprocessing

In [13]:
tokenizer = Tokenizer(oov_token='<OOV>')

In [14]:
# Fit the tokenizer on the short descriptions
tokenizer.fit_on_texts(data['short_description'])

In [15]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'is': 8,
 'that': 9,
 'for': 10,
 'i': 11,
 'you': 12,
 'on': 13,
 'it': 14,
 'with': 15,
 'are': 16,
 'we': 17,
 'be': 18,
 'this': 19,
 'as': 20,
 'have': 21,
 'was': 22,
 'but': 23,
 'not': 24,
 'your': 25,
 'at': 26,
 'from': 27,
 'my': 28,
 'an': 29,
 'or': 30,
 'about': 31,
 'has': 32,
 'more': 33,
 'our': 34,
 'by': 35,
 'can': 36,
 'one': 37,
 'what': 38,
 'all': 39,
 'when': 40,
 'their': 41,
 'will': 42,
 'they': 43,
 'out': 44,
 'who': 45,
 "it's": 46,
 'his': 47,
 'if': 48,
 'new': 49,
 'he': 50,
 'time': 51,
 'just': 52,
 'up': 53,
 'people': 54,
 'so': 55,
 'her': 56,
 'do': 57,
 'like': 58,
 'how': 59,
 'some': 60,
 'there': 61,
 'been': 62,
 'said': 63,
 'no': 64,
 'than': 65,
 'us': 66,
 'me': 67,
 'most': 68,
 'year': 69,
 'after': 70,
 'get': 71,
 'day': 72,
 'life': 73,
 'she': 74,
 'had': 75,
 'many': 76,
 'would': 77,
 'into': 78,
 'were': 79,
 'make': 80,
 'these': 81,
 'first': 82,
 'over': 83,
 'them': 84,
 'know': 85,
 'now': 86,
 'even': 87,
 'years': 88,
 'may': 89,
 'want': 90,
 'world': 91,
 'its': 92,
 "don't": 93,
 'way': 94,
 'other': 95,
 'two': 96,
 'only': 97,
 'could': 98,
 'being': 99,
 'trump': 100,
 'while': 101,
 'love': 102,
 'which': 103,
 'president': 104,
 'also': 105,
 'because': 106,
 'think': 107,
 'much': 108,
 'good': 109,
 'take': 110,
 'here': 111,
 'need': 112,
 'last': 113,
 'see': 114,
 'back': 115,
 'those': 116,
 'week': 117,
 'say': 118,
 '”': 119,
 'should': 120,
 'best': 121,
 'every': 122,
 'still': 123,
 'right': 124,
 'old': 125,
 'go': 126,
 'before': 127,
 'where': 128,
 'women': 129,
 'things': 130,
 's': 131,
 'work': 132,
 'u': 133,
 'health': 134,
 'through': 135,
 'never': 136,
 'too': 137,
 'look': 138,
 'really': 139,
 'well': 140,
 'something': 141,
 "you're": 142,
 'help': 143,
 'why': 144,
 'down': 145,
 'little': 146,
 'going': 147,
 'any': 148,
 'long': 149,
 'children': 150,
 'own': 151,
 'off': 152,
 'made': 153,
 'very': 154,
 'home': 155,
 'family': 156,
 'says': 157,
 "i'm": 158,
 'around': 159,
 'better': 160,
 'find': 161,
 'few': 162,
 'feel': 163,
 'him': 164,
 'state': 165,
 'great': 166,
 'show': 167,
 'always': 168,
 'then': 169,
 'ever': 170,
 'come': 171,
 'kids': 172,
 'did': 173,
 'news': 174,
 'change': 175,
 'american': 176,
 'big': 177,
 'during': 178,
 'check': 179,
 'another': 180,
 'since': 181,
 'might': 182,
 'am': 183,
 'days': 184,
 'often': 185,
 'sure': 186,
 'house': 187,
 'part': 188,
 'three': 189,
 'food': 190,
 'thing': 191,
 'between': 192,
 "we're": 193,
 'against': 194,
 'got': 195,
 'both': 196,
 'school': 197,
 'country': 198,
 "there's": 199,
 'keep': 200,
 "that's": 201,
 'without': 202,
 'each': 203,
 'does': 204,
 'white': 205,
 'same': 206,
 'comes': 207,
 'found': 208,
 'next': 209,
 'city': 210,
 'donald': 211,
 'whether': 212,
 'lot': 213,
 'today': 214,
 'care': 215,
 "doesn't": 216,
 'high': 217,
 'important': 218,
 'live': 219,
 'place': 220,
 'real': 221,
 'making': 222,
 'former': 223,
 'end': 224,
 'man': 225,
 'getting': 226,
 "can't": 227,
 'night': 228,
 'told': 229,
 'york': 230,
 'parents': 231,
 'hard': 232,
 'lives': 233,
 'yet': 234,
 'give': 235,
 'become': 236,
 'past': 237,
 'child': 238,
 'away': 239,
 'again': 240,
 'black': 241,
 'enough': 242,
 'national': 243,
 'use': 244,
 'put': 245,
 'yourself': 246,
 'called': 247,
 "i've": 248,
 'public': 249,
 'twitter': 250,
 '1': 251,
 "isn't": 252,
 'different': 253,
 'states': 254,
 'once': 255,
 'times': 256,
 'let': 257,
 'having': 258,
 'must': 259,
 'believe': 260,
 'others': 261,
 "didn't": 262,
 'facebook': 263,
 '10': 264,
 'huffpost': 265,
 'experience': 266,
 'start': 267,
 'season': 268,
 'read': 269,
 'person': 270,
 'style': 271,
 'less': 272,
 'young': 273,
 'social': 274,
 'such': 275,
 'men': 276,
 'media': 277,
 'five': 278,
 'wedding': 279,
 'video': 280,
 'least': 281,
 'someone': 282,
 'doing': 283,
 'face': 284,
 'top': 285,
 'thought': 286,
 'everyone': 287,
 'story': 288,
 'ago': 289,
 'far': 290,
 'money': 291,
 'americans': 292,
 'america': 293,
 'study': 294,
 'according': 295,
 'looking': 296,
 'police': 297,
 'ways': 298,
 'together': 299,
 'actually': 300,
 'easy': 301,
 'used': 302,
 'it’s': 303,
 'tell': 304,
 'summer': 305,
 'party': 306,
 'woman': 307,
 'star': 308,
 'friends': 309,
 'million': 310,
 'nothing': 311,
 'though': 312,
 'set': 313,
 'stop': 314,
 'full': 315,
 'percent': 316,
 'heart': 317,
 'took': 318,
 'makes': 319,
 'moment': 320,
 'recent': 321,
 'self': 322,
 'everything': 323,
 '000': 324,
 'already': 325,
 'sometimes': 326,
 'month': 327,
 "they're": 328,
 'body': 329,
 'history': 330,
 'campaign': 331,
 'political': 332,
 'government': 333,
 'taking': 334,
 '—': 335,
 'bad': 336,
 'months': 337,
 'try': 338,
 'support': 339,
 'four': 340,
 'trying': 341,
 'living': 342,
 'under': 343,
 'power': 344,
 "we've": 345,
 'business': 346,
 'list': 347,
 'below': 348,
 'job': 349,
 'favorite': 350,
 'matter': 351,
 'mind': 352,
 'united': 353,
 'future': 354,
 'healthy': 355,
 'working': 356,
 'fashion': 357,
 "he's": 358,
 'talk': 359,
 'human': 360,
 'fact': 361,
 'call': 362,
 'republican': 363,
 'free': 364,
 'mother': 365,
 'divorce': 366,
 'sleep': 367,
 'law': 368,
 'community': 369,
 'question': 370,
 'means': 371,
 'happy': 372,
 'travel': 373,
 'until': 374,
 'left': 375,
 'small': 376,
 'film': 377,
 'case': 378,
 'kind': 379,
 'seems': 380,
 'death': 381,
 'perfect': 382,
 'second': 383,
 'true': 384,
 'known': 385,
 'asked': 386,
 '2': 387,
 'point': 388,
 'came': 389,
 'across': 390,
 'recently': 391,
 'post': 392,
 'seen': 393,
 'rights': 394,
 'group': 395,
 'age': 396,
 'hope': 397,
 'needs': 398,
 'war': 399,
 'instead': 400,
 'obama': 401,
 "here's": 402,
 'head': 403,
 'remember': 404,
 'mean': 405,
 'watch': 406,
 'move': 407,
 'late': 408,
 'myself': 409,
 'learn': 410,
 'cancer': 411,
 'court': 412,
 'anything': 413,
 'almost': 414,
 'music': 415,
 'however': 416,
 'baby': 417,
 'marriage': 418,
 'probably': 419,
 'pretty': 420,
 'likely': 421,
 "you've": 422,
 'simple': 423,
 'bill': 424,
 'company': 425,
 'share': 426,
 'election': 427,
 'holiday': 428,
 'behind': 429,
 'maybe': 430,
 'able': 431,
 'relationship': 432,
 'problem': 433,
 'com': 434,
 'based': 435,
 'coming': 436,
 'idea': 437,
 'among': 438,
 'game': 439,
 'wanted': 440,
 'words': 441,
 'fear': 442,
 'wrong': 443,
 'early': 444,
 'open': 445,
 "you'll": 446,
 'mom': 447,
 'shows': 448,
 'fun': 449,
 'photos': 450,
 'number': 451,
 'students': 452,
 'deal': 453,
 'name': 454,
 'especially': 455,
 '5': 456,
 'personal': 457,
 'college': 458,
 'course': 459,
 'done': 460,
 'anyone': 461,
 'feeling': 462,
 "won't": 463,
 'host': 464,
 'including': 465,
 'research': 466,
 'major': 467,
 'yes': 468,
 'presidential': 469,
 "trump's": 470,
 'ask': 471,
 'art': 472,
 'whole': 473,
 'run': 474,
 'play': 475,
 'gop': 476,
 'plan': 477,
 'latest': 478,
 'act': 479,
 'decision': 480,
 'sense': 481,
 'fall': 482,
 'thinking': 483,
 'hit': 484,
 'started': 485,
 'washington': 486,
 'water': 487,
 'bring': 488,
 'ourselves': 489,
 'eat': 490,
 '3': 491,
 'process': 492,
 'daughter': 493,
 'federal': 494,
 'gay': 495,
 'climate': 496,
 'wants': 497,
 'single': 498,
 'turn': 499,
 'went': 500,
 'rather': 501,
 'possible': 502,
 'special': 503,
 'order': 504,
 'several': 505,
 'nearly': 506,
 'friday': 507,
 'weekend': 508,
 'clinton': 509,
 'attention': 510,
 'photo': 511,
 'weight': 512,
 'ready': 513,
 'six': 514,
 'clear': 515,
 'system': 516,
 'daily': 517,
 'lost': 518,
 'office': 519,
 'looks': 520,
 '20': 521,
 'seem': 522,
 'understand': 523,
 'weeks': 524,
 'common': 525,
 'son': 526,
 'hours': 527,
 'series': 528,
 'red': 529,
 'reason': 530,
 'morning': 531,
 'beautiful': 532,
 "aren't": 533,
 'step': 534,
 'issue': 535,
 "what's": 536,
 'leave': 537,
 'control': 538,
 'create': 539,
 'heard': 540,
 'along': 541,
 'book': 542,
 'movie': 543,
 'girl': 544,
 'half': 545,
 'line': 546,
 'eating': 547,
 'reality': 548,
 "let's": 549,
 'stay': 550,
 'university': 551,
 'democratic': 552,
 'husband': 553,
 'room': 554,
 'pay': 555,
 'stress': 556,
 'sunday': 557,
 'don’t': 558,
 'role': 559,
 'team': 560,
 'finally': 561,
 'takes': 562,
 'given': 563,
 'sex': 564,
 'education': 565,
 'couple': 566,
 'pinterest': 567,
 'simply': 568,
 'security': 569,
 'bit': 570,
 '4': 571,
 'risk': 572,
 'side': 573,
 'action': 574,
 'questions': 575,
 'hair': 576,
 'stories': 577,
 'opportunity': 578,
 'using': 579,
 'republicans': 580,
 "she's": 581,
 'issues': 582,
 'families': 583,
 'policy': 584,
 'violence': 585,
 'sexual': 586,
 'energy': 587,
 'short': 588,
 'taken': 589,
 'lead': 590,
 'themselves': 591,
 '2012': 592,
 'culture': 593,
 'friend': 594,
 'despite': 595,
 'quite': 596,
 'longer': 597,
 'truth': 598,
 'following': 599,
 'tv': 600,
 'online': 601,
 'international': 602,
 'giving': 603,
 'within': 604,
 'felt': 605,
 'report': 606,
 'girls': 607,
 'close': 608,
 'justice': 609,
 'saying': 610,
 'leaders': 611,
 'hear': 612,
 'else': 613,
 'growing': 614,
 'killed': 615,
 'happen': 616,
 'global': 617,
 'light': 618,
 'perhaps': 619,
 'researchers': 620,
 'space': 621,
 'vote': 622,
 'knew': 623,
 'air': 624,
 'local': 625,
 'stand': 626,
 'fight': 627,
 'trip': 628,
 'practice': 629,
 'running': 630,
 'learned': 631,
 'general': 632,
 'director': 633,
 'disease': 634,
 'word': 635,
 'beauty': 636,
 "wasn't": 637,
 'north': 638,
 'spring': 639,
 'continue': 640,
 'gets': 641,
 'key': 642,
 'anti': 643,
 'saturday': 644,
 'rest': 645,
 'break': 646,
 'difficult': 647,
 'officials': 648,
 'outside': 649,
 'administration': 650,
 'win': 651,
 'industry': 652,
 'truly': 653,
 'information': 654,
 '2013': 655,
 'tips': 656,
 'spend': 657,
 'middle': 658,
 'although': 659,
 'alone': 660,
 'event': 661,
 'medical': 662,
 '30': 663,
 'talking': 664,
 'south': 665,
 'spent': 666,
 'forward': 667,
 'present': 668,
 'wrote': 669,
 'street': 670,
 'strong': 671,
 'hot': 672,
 'race': 673,
 'hand': 674,
 'attack': 675,
 'members': 676,
 'financial': 677,
 'hillary': 678,
 'focus': 679,
 'choice': 680,
 'hold': 681,
 'died': 682,
 'biggest': 683,
 'society': 684,
 'click': 685,
 'inside': 686,
 'nation': 687,
 'success': 688,
 '12': 689,
 'john': 690,
 'later': 691,
 '7': 692,
 '6': 693,
 'goes': 694,
 'dress': 695,
 'service': 696,
 'loss': 697,
 'center': 698,
 'worth': 699,
 'ones': 700,
 'needed': 701,
 'actress': 702,
 '2014': 703,
 'senate': 704,
 'turned': 705,
 'soon': 706,
 'popular': 707,
 'career': 708,
 'serious': 709,
 'actor': 710,
 'mental': 711,
 'beyond': 712,
 'level': 713,
 'answer': 714,
 'either': 715,
 'happened': 716,
 'above': 717,
 '15': 718,
 'amazing': 719,
 '“i': 720,
 'consider': 721,
 'powerful': 722,
 'class': 723,
 'changes': 724,
 'california': 725,
 'congress': 726,
 'companies': 727,
 'offer': 728,
 'cannot': 729,
 'positive': 730,
 'color': 731,
 'co': 732,
 'department': 733,
 'visit': 734,
 'decades': 735,
 'front': 736,
 'saw': 737,
 'chance': 738,
 'married': 739,
 'low': 740,
 'choose': 741,
 'tax': 742,
 'father': 743,
 'parent': 744,
 'deep': 745,
 'enjoy': 746,
 'exactly': 747,
 'certain': 748,
 'shot': 749,
 'released': 750,
 'term': 751,
 'monday': 752,
 'wife': 753,
 'candidate': 754,
 'follow': 755,
 'd': 756,
 'planning': 757,
 'thousands': 758,
 'super': 759,
 'singer': 760,
 'eyes': 761,
 'certainly': 762,
 'decided': 763,
 'announced': 764,
 'countries': 765,
 'loved': 766,
 'march': 767,
 'seven': 768,
 'problems': 769,
 'meet': 770,
 'cause': 771,
 'touch': 772,
 'tuesday': 773,
 'pain': 774,
 'born': 775,
 'christmas': 776,
 'natural': 777,
 'gun': 778,
 'democrats': 779,
 'toward': 780,
 'secret': 781,
 'crisis': 782,
 'car': 783,
 'happens': 784,
 'winter': 785,
 'technology': 786,
 'upon': 787,
 'met': 788,
 'military': 789,
 'message': 790,
 'economic': 791,
 'impact': 792,
 'moments': 793,
 '8': 794,
 'celebrate': 795,
 'reasons': 796,
 'emotional': 797,
 'leader': 798,
 'places': 799,
 'internet': 800,
 'cut': 801,
 'became': 802,
 'debate': 803,
 'fans': 804,
 'challenge': 805,
 '100': 806,
 'large': 807,
 'published': 808,
 'response': 809,
 'brought': 810,
 'i’m': 811,
 '11': 812,
 'non': 813,
 'instagram': 814,
 'ideas': 815,
 'whose': 816,
 'ahead': 817,
 'reportedly': 818,
 'hotel': 819,
 'dream': 820,
 'tumblr': 821,
 'walk': 822,
 'potential': 823,
 'safe': 824,
 'gift': 825,
 'dead': 826,
 'current': 827,
 '50': 828,
 'fast': 829,
 'knows': 830,
 'wall': 831,
 'watching': 832,
 'peace': 833,
 'gave': 834,
 'third': 835,
 'road': 836,
 'hate': 837,
 '2016': 838,
 'senator': 839,
 'created': 840,
 'gone': 841,
 'science': 842,
 'imagine': 843,
 'data': 844,
 'reported': 845,
 'record': 846,
 'began': 847,
 'events': 848,
 'dad': 849,
 'program': 850,
 'plans': 851,
 'earlier': 852,
 'millions': 853,
 'honor': 854,
 'unique': 855,
 'advice': 856,
 "'": 857,
 'michael': 858,
 'entire': 859,
 'press': 860,
 'brain': 861,
 'sweet': 862,
 'forget': 863,
 'held': 864,
 'force': 865,
 'secretary': 866,
 'drug': 867,
 'lose': 868,
 'accused': 869,
 'access': 870,
 'exercise': 871,
 'town': 872,
 'challenges': 873,
 'project': 874,
 'worst': 875,
 'student': 876,
 'workers': 877,
 'nature': 878,
 "i'd": 879,
 'results': 880,
 'voters': 881,
 'learning': 882,
 'form': 883,
 'interview': 884,
 'fire': 885,
 'market': 886,
 'journey': 887,
 'whatever': 888,
 'effort': 889,
 'wear': 890,
 'difference': 891,
 'finding': 892,
 '9': 893,
 'happiness': 894,
 'wait': 895,
 'begin': 896,
 'speak': 897,
 'provide': 898,
 'legal': 899,
 'expected': 900,
 'itself': 901,
 'conversation': 902,
 'san': 903,
 'movement': 904,
 'thursday': 905,
 'huge': 906,
 'realize': 907,
 'hands': 908,
 'wonder': 909,
 'yoga': 910,
 'park': 911,
 'sign': 912,
 'benefits': 913,
 'minutes': 914,
 'foods': 915,
 'near': 916,
 'july': 917,
 'patients': 918,
 'view': 919,
 'save': 920,
 'claims': 921,
 'judge': 922,
 'relationships': 923,
 'treatment': 924,
 'changed': 925,
 'experts': 926,
 'ability': 927,
 'm': 928,
 'supreme': 929,
 'vacation': 930,
 'expect': 931,
 'led': 932,
 'weather': 933,
 'model': 934,
 "couldn't": 935,
 'buy': 936,
 'rules': 937,
 'guy': 938,
 "world's": 939,
 'kid': 940,
 'evidence': 941,
 'attorney': 942,
 'dr': 943,
 'trump’s': 944,
 'c': 945,
 'dinner': 946,
 'dog': 947,
 'politics': 948,
 'stars': 949,
 'reports': 950,
 'wednesday': 951,
 'beach': 952,
 'cost': 953,
 'avoid': 954,
 'calling': 955,
 'himself': 956,
 'david': 957,
 'parenting': 958,
 'comments': 959,
 'jobs': 960,
 'protect': 961,
 'usually': 962,
 'boy': 963,
 'allow': 964,
 'paris': 965,
 "year's": 966,
 'modern': 967,
 'shooting': 968,
 'texas': 969,
 'looked': 970,
 'official': 971,
 'fresh': 972,
 'thanks': 973,
 'becoming': 974,
 'inspired': 975,
 'surprise': 976,
 'moms': 977,
 'tried': 978,
 "wouldn't": 979,
 'couples': 980,
 'eye': 981,
 'sports': 982,
 'groups': 983,
 'completely': 984,
 'works': 985,
 'cities': 986,
 'beginning': 987,
 'moving': 988,
 'earth': 989,
 'joy': 990,
 'fox': 991,
 'playing': 992,
 'seeing': 993,
 'freedom': 994,
 'reuters': 995,
 'west': 996,
 'credit': 997,
 'god': 998,
 'quickly': 999,
 '19': 1000,
 ...}

In [31]:
# Count of unique words in the dataset
vocab_size=len(tokenizer.word_index)

In [17]:
# Convert the short descriptions to sequences of integers
tokenizer.texts_to_sequences(data['short_description'])

[[134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131,
  2888,
  10,
  2,
  482],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637,
  519,
  7,
  1095,
  1172],
 [374, 12, 21, 4, 947, 12, 93, 523, 38, 98, 18, 4988],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409,
  14059,
  7,
  31410,
  3058],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313,
  911,
  3045,
  500,
  2362],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845,
  56,
  1285,
  1303,
  63],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74,
  3895,
  53,
  29,
  884],
 [33,
  65,
  545,
  4,
  310,
  54,
  4235,
  202,
  487,
  696,
  189,
  184,
  70,
  2,
  1617,
  14610,
  2,
  133,
  131,
  4346],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4,
  33,
  9153,
  1537,
  288],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116,
  6,
  92,
  3954,
  399],
 [7985,
  32,
  171,
  343,
  1304,
  27,
  505,
  1610,
  2518,
  48045,
  45,
  90,
  3,
  339,
  4,
  360,
  394,
  331,
  194,
  1988,
  26,
  2,
  91,
  2042],
 [2,
  1778,
  13560,
  4,
  614,
  2528,
  5,
  2392,
  194,
  2,
  5132,
  10,
  15872,
  10534,
  45,
  22,
  37,
  5,
  2,
  68,
  7076,
  611,
  7,
  22802,
  3079,
  948],
 [2132,
  21143,
  14610,
  2,
  12203,
  6,
  21144,
  2848,
  6,
  22,
  7441,
  3,
  6418,
  237,
  13561,
  691,
  19,
  117],
 [37,
  4079,
  921,
  9,
  50,
  21145,
  54,
  13,
  2,
  2709,
  1655,
  505,
  707,
  31411,
  3,
  721,
  4,
  31412,
  8461],
 [1288,
  2220,
  2221,
  2433,
  2,
  753,
  5,
  929,
  412,
  609,
  13562,
  2433,
  32,
  2849,
  3,
  3755,
  7,
  4,
  9761,
  884,
  15,
  2,
  187,
  3124,
  3080,
  2,
  2542,
  693,
  9999],
 [48046,
  846,
  1451,
  628,
  3,
  6168,
  621,
  737,
  164,
  8970,
  989,
  692,
  48047,
  256,
  6,
  373,
  506,
  37177,
  310,
  1337],
 [3811,
  24912,
  858,
  642,
  8971,
  24913,
  6,
  6608,
  27539,
  2,
  12624,
  167,
  2675,
  2,
  5744,
  5,
  4,
  7705,
  444,
  13563,
  8462],
 [24914,
  24915,
  45,
  1174,
  2,
  1095,
  1172,
  12625,
  651,
  189,
  91,
  528,
  6794,
  15,
  47,
  2902,
  6088,
  12626,
  32,
  682],
 [2,
  15232,
  6,
  48048,
  6419,
  3046,
  1002,
  3,
  7706,
  53,
  340,
  5133,
  98,
  313,
  2,
  1059,
  10,
  4611,
  3,
  10535,
  2,
  399],
 [2,
  12203,
  6,
  21144,
  2848,
  333,
  5410,
  4,
  17525,
  20,
  2,
  13564,
  1617,
  1746,
  3837,
  15873,
  2879,
  83,
  2,
  8312,
  3333,
  6,
  3508,
  4655],
 [10,
  2,
  237,
  1164,
  337,
  1092,
  32,
  3202,
  27540,
  2,
  5042,
  70,
  950,
  9,
  2,
  48049,
  10536,
  676,
  5,
  813,
  176,
  2549,
  1378,
  64,
  241,
  676],
 [104, 582, 6874, 20, 3923, 15, 1120, 1271],
 [2,
  1617,
  5959,
  44,
  2,
  344,
  8619,
  6,
  8785,
  9154,
  6,
  24916,
  7,
  3508,
  4655,
  128,
  2,
  1189,
  63,
  2,
  2230,
  22,
  48050,
  119],
 [2,
  498,
  6795,
  2075,
  22,
  6246,
  7,
  2,
  243,
  5286,
  624,
  4850,
  13,
  557,
  40,
  14,
  5287,
  78,
  4,
  1206,
  1528,
  2,
  4018,
  648,
  63],
 [29, 1093, 1771, 318, 13, 4, 253, 163, 20, 5357, 6026, 8149, 78, 72, 37178],
 [1073,
  37179,
  4,
  4261,
  2393,
  6,
  5288,
  13070,
  22,
  8620,
  7,
  2930,
  7,
  1425,
  3222],
 [2644, 2363, 136, 75, 4, 1370, 982, 3236, 335, 374, 557],
 [104,
  1506,
  1918,
  6,
  82,
  1386,
  6796,
  1918,
  79,
  438,
  758,
  5,
  16638,
  335,
  27,
  3461,
  6,
  2828,
  3,
  6797,
  6,
  91,
  611,
  335,
  3,
  555,
  41,
  8972],
 [2,
  13565,
  633,
  63,
  2645,
  5,
  47,
  2568,
  543,
  16,
  123,
  4055,
  15,
  323,
  1489,
  44,
  61,
  81,
  184],
 [22803,
  1512,
  385,
  20,
  2,
  1175,
  6798,
  225,
  32,
  10000,
  2,
  37180,
  21146,
  6,
  2,
  4379,
  165,
  1011],
 [133,
  131,
  104,
  1506,
  1918,
  7,
  1052,
  10,
  2,
  5132,
  5,
  1758,
  2504,
  3258,
  157,
  47,
  317,
  500,
  44,
  3,
  2,
  2325,
  156,
  2550,
  2,
  48051,
  381,
  375,
  4,
  37181,
  3334,
  119],
 [595,
  3669,
  2114,
  654,
  41,
  132,
  637,
  48052,
  1318,
  6,
  7,
  60,
  1012,
  2,
  6695,
  22804,
  1054,
  10537,
  2,
  519,
  5,
  11111,
  632,
  845],
 [13, 752, 2, 4262, 82, 249, 12627, 5, 4236, 2685, 2326, 9340, 6, 4380, 13566],
 [2, 1000, 69, 125, 818, 5659, 78, 2, 21147, 7, 4, 1580, 4080, 3, 2337, 297],
 [7307,
  264,
  88,
  54,
  42,
  18,
  5745,
  3,
  2,
  1634,
  8621,
  1617,
  20,
  4,
  14060,
  1617,
  119],
 [3508,
  4655,
  22,
  343,
  4,
  2132,
  406,
  644,
  20,
  2,
  1617,
  27541,
  1594,
  2,
  133,
  131,
  4346],
 [2,
  91,
  134,
  1243,
  8,
  1629,
  2,
  4896,
  31,
  4,
  48053,
  48054,
  7,
  2,
  1342,
  5,
  2,
  2307,
  9154,
  7,
  4487,
  19,
  305,
  20,
  1309,
  6,
  662,
  877,
  13,
  2,
  1155,
  673,
  3,
  1131,
  8786,
  5,
  48055,
  6,
  95,
  2986],
 [1279,
  21,
  3335,
  2060,
  9,
  1997,
  249,
  650,
  5,
  487,
  4897,
  1598,
  132,
  335,
  23,
  1489,
  86,
  13,
  2,
  1228,
  7,
  5535],
 [16639,
  7,
  2,
  330,
  5,
  2,
  48056,
  6875,
  519,
  32,
  4,
  3462,
  5,
  13567,
  932,
  66,
  3,
  31413,
  4656,
  119,
  3336,
  858,
  822,
  229,
  2,
  277],
 [2,
  633,
  5,
  2,
  1289,
  13568,
  377,
  4754,
  4,
  1515,
  5,
  2,
  1870,
  5813,
  10,
  2,
  3534,
  5239,
  7,
  2,
  7442,
  6027,
  4851],
 [363,
  3704,
  83,
  2,
  16640,
  133,
  131,
  7842,
  27,
  2930,
  6876,
  13071,
  339,
  10,
  48057,
  2125],
 [2725,
  5475,
  13072,
  518,
  29,
  981,
  6,
  32,
  1871,
  5,
  1792,
  686,
  56,
  329,
  27,
  4,
  21148,
  19732,
  14611,
  4898,
  9,
  615,
  56,
  1928,
  6,
  189,
  95,
  241,
  607,
  686,
  29,
  2819,
  1353,
  7843,
  88,
  289],
 [4,
  10256,
  487,
  7844,
  32,
  62,
  6169,
  10,
  19733,
  1571,
  6,
  2,
  165,
  42,
  314,
  10001,
  44,
  364,
  10820,
  487,
  13,
  644],
 [1074,
  14612,
  5,
  2,
  48058,
  335,
  37182,
  4693,
  630,
  167,
  335,
  8,
  3059,
  3,
  608,
  7,
  1835,
  31414,
  4,
  2006,
  5,
  392,
  2512,
  19734,
  7,
  2231,
  7443,
  7,
  49,
  230],
 [2,
  223,
  205,
  187,
  1003,
  5,
  1433,
  32,
  705,
  83,
  2455,
  20,
  188,
  5,
  4,
  494,
  1132,
  78,
  2,
  2542,
  693,
  10538,
  1325,
  13,
  2,
  2952],
 [2,
  12628,
  176,
  15874,
  49,
  542,
  48059,
  22,
  3483,
  2529,
  256,
  335,
  374,
  74,
  500,
  2176,
  3,
  56,
  1904,
  10,
  339],
 [48060,
  6609,
  6965,
  3,
  2,
  3644,
  2019,
  6,
  864,
  145,
  56,
  16641,
  374,
  297,
  1922,
  7707,
  19,
  637,
  2,
  82,
  51,
  6609,
  89,
  21,
  3203,
  4,
  73],
 [2,
  1965,
  2071,
  63,
  74,
  1190,
  44,
  10,
  278,
  527,
  4,
  72,
  10,
  56,
  559,
  7,
  2,
  49,
  574,
  543],
 [2,
  548,
  308,
  229,
  1006,
  11112,
  581,
  27542,
  44,
  106,
  1421,
  46,
  24,
  356,
  888,
  811,
  283],
 [2,
  2644,
  2363,
  37183,
  16,
  1977,
  3,
  161,
  44,
  45,
  749,
  2,
  4755,
  3081,
  2028,
  88,
  289],
 [2,
  3617,
  1060,
  2394,
  1661,
  308,
  2314,
  150,
  26,
  2,
  3727,
  37184,
  197,
  7,
  8973,
  5891,
  3,
  80,
  2,
  2133],
 [10821,
  2,
  223,
  133,
  131,
  4525,
  3,
  2,
  353,
  1662,
  6,
  4,
  3777,
  37185,
  7,
  7986,
  3924,
  864,
  4612,
  15,
  1149,
  611],
 [2,
  1490,
  1213,
  1950,
  518,
  3838,
  251,
  456,
  310,
  3259,
  2260,
  3,
  92,
  10538,
  850],
 [205,
  187,
  860,
  866,
  37186,
  4081,
  9155,
  63,
  4,
  9762,
  4694,
  8,
  24,
  4082,
  6,
  77,
  2676,
  583,
  20,
  140,
  20,
  2093],
 [2,
  2400,
  632,
  31415,
  8,
  7578,
  3,
  284,
  223,
  24917,
  1966,
  21149,
  37187,
  1293,
  7,
  2,
  632,
  427],
 [4,
  133,
  131,
  2776,
  9,
  15233,
  2114,
  601,
  921,
  950,
  9,
  8974,
  10,
  654,
  31,
  3379,
  174,
  4488,
  13,
  16642,
  16,
  421,
  3,
  499,
  53,
  880,
  12204,
  15,
  7708],
 [13, 4, 5411, 2155, 2094, 2410, 3260, 251, 70, 4, 3618, 1198, 7, 917],
 [2, 633, 22, 121, 385, 10, 2, 7192, 543, 14061],
 [328,
  5892,
  10,
  6799,
  3987,
  43,
  118,
  42,
  143,
  1367,
  1765,
  215,
  35,
  10539,
  48061,
  12629,
  9,
  21,
  22805,
  7,
  2,
  2512],
 [411,
  204,
  24,
  7579,
  529,
  6,
  1150,
  2,
  104,
  63,
  752,
  4570,
  411,
  8,
  141,
  17,
  36,
  57,
  299],
 [45,
  17,
  21,
  13,
  2,
  1206,
  8,
  45,
  1656,
  2861,
  475,
  119,
  1890,
  229,
  991,
  174,
  557],
 [2,
  31416,
  4451,
  118,
  31417,
  2095,
  463,
  21,
  3,
  6170,
  15,
  2,
  3866,
  30,
  1151,
  13569,
  6,
  2348,
  22806,
  256,
  3,
  1393,
  41,
  1219],
 [48062, 13073, 1650, 15, 2, 3125, 22807, 6, 485, 47, 368, 2660, 708, 7, 838],
 [779,
  7,
  2,
  7444,
  33,
  4756,
  187,
  1851,
  16,
  4990,
  45,
  42,
  110,
  13,
  4,
  707,
  363,
  223,
  1966],
 [1918,
  851,
  3,
  2726,
  510,
  3,
  4,
  49,
  22808,
  3046,
  294,
  9,
  5289,
  3,
  12205,
  579,
  1286,
  2686,
  3,
  1581,
  194,
  1638,
  7580],
 [2,
  466,
  435,
  1078,
  32,
  208,
  5536,
  298,
  3,
  4413,
  2470,
  31,
  1036,
  6344,
  3237,
  6,
  1294,
  7,
  56,
  6247],
 [303,
  24,
  31,
  37188,
  30,
  87,
  27543,
  2,
  3099,
  5,
  19735,
  37189,
  501,
  2,
  49,
  2020,
  6345,
  47,
  2232,
  335,
  122,
  17526,
  5,
  14],
 [7987,
  48063,
  6514,
  22809,
  48064,
  7,
  2,
  133,
  131,
  445,
  1121,
  3,
  3509,
  47,
  82,
  1657,
  6420,
  26,
  396,
  1000,
  6,
  236,
  2,
  5660,
  225,
  3,
  407,
  53,
  3,
  64,
  251,
  7,
  2,
  11815],
 [7077,
  153,
  1441,
  194,
  4,
  906,
  2384,
  725,
  12206,
  9,
  22,
  123,
  614,
  6,
  2889,
  758,
  5,
  2246,
  1379],
 [104,
  1506,
  1918,
  32,
  3082,
  2,
  2987,
  1408,
  5,
  2,
  3273,
  812,
  1220,
  334,
  188,
  7,
  4,
  10540,
  24918,
  6877,
  1950,
  864,
  26,
  2,
  6089,
  343,
  4,
  5043,
  2879],
 [1634,
  9156,
  1333,
  4,
  388,
  10,
  3425,
  13,
  2,
  4899,
  1220,
  48065,
  243,
  569,
  48066,
  13071,
  4,
  133,
  131,
  27544,
  13,
  37190,
  2789],
 [2,
  2699,
  37,
  5,
  2,
  264,
  683,
  11458,
  344,
  8463,
  7,
  2,
  91,
  32,
  62,
  8150,
  35,
  1149,
  1413,
  181,
  444,
  7,
  2,
  399,
  103,
  3082,
  92,
  21150,
  72,
  13,
  557],
 [48067,
  4191,
  8,
  1257,
  20,
  2,
  1124,
  4943,
  1179,
  6,
  42,
  421,
  1030,
  1304,
  10,
  24919,
  6,
  176,
  2162,
  3,
  4192,
  2,
  3705,
  20,
  140],
 [2,
  609,
  733,
  1939,
  96,
  3955,
  4452,
  10,
  2,
  559,
  944,
  560,
  1939,
  4,
  3955,
  922,
  6,
  4,
  1877],
 [2,
  633,
  229,
  2,
  1891,
  50,
  22,
  759,
  1639,
  3,
  18,
  561,
  7078,
  53,
  543,
  96,
  335,
  20,
  50,
  32,
  189,
  2931,
  21151,
  7,
  2,
  985],
 [8151,
  1427,
  7308,
  764,
  9,
  3178,
  42,
  18,
  2308,
  115,
  7,
  96,
  1022,
  128,
  4,
  6421,
  3337,
  2968,
  32,
  153,
  1257,
  5134],
 [70,
  4,
  264,
  72,
  1852,
  2528,
  9,
  506,
  3597,
  2,
  12630,
  8619,
  1940,
  725,
  195,
  5537,
  933,
  23,
  105,
  4,
  14613,
  3577,
  1617],
 [6421, 1413, 16, 3896, 49, 688, 7, 41, 48068, 194, 1149, 1413, 7, 2, 1105],
 [22810,
  1499,
  67,
  7,
  4,
  1468,
  5,
  8464,
  10,
  2790,
  88,
  5,
  696,
  119,
  2,
  1272,
  308,
  229,
  2,
  1759,
  70,
  50,
  14614,
  47,
  6028,
  2543,
  2737,
  1063],
 [48069,
  48070,
  4852,
  98,
  18,
  4,
  467,
  2850,
  3,
  2,
  1293,
  1538,
  5290,
  397,
  5,
  19736],
 [196,
  1319,
  6,
  602,
  7445,
  854,
  2,
  2544,
  5,
  2,
  133,
  48071,
  131,
  4693,
  18583,
  14615],
 [2,
  1000,
  69,
  125,
  760,
  7446,
  6,
  2401,
  3081,
  42,
  1507,
  2,
  8621,
  48072,
  1326,
  10,
  56,
  679,
  13,
  643,
  3060,
  1002],
 [1464,
  27,
  27545,
  7309,
  21152,
  63,
  765,
  7447,
  33,
  1233,
  10,
  496,
  175,
  120,
  21,
  1456,
  19,
  805],
 [5592,
  1546,
  249,
  7310,
  1512,
  48073,
  22,
  1726,
  7,
  2,
  4613,
  12631,
  5,
  2513,
  2661,
  45,
  75,
  62,
  3080,
  47,
  519],
 [2, 800, 10822, 7, 3598, 83, 2, 223, 82, 10823, 8622, 680, 10, 2, 7193, 72],
 [2,
  710,
  63,
  50,
  22,
  55,
  4489,
  37191,
  101,
  968,
  2,
  528,
  5893,
  9,
  50,
  6422,
  10,
  47,
  73,
  6,
  22,
  1618,
  1812,
  2,
  3261,
  101,
  4695],
 [4019,
  5,
  2,
  1853,
  1836,
  27546,
  153,
  2,
  22806,
  16643,
  19737,
  23,
  2,
  2400,
  1624,
  412,
  3483,
  9,
  3061],
 [2,
  2021,
  157,
  2619,
  2727,
  7709,
  14616,
  3,
  2620,
  210,
  13570,
  319,
  14,
  647,
  10,
  54,
  579,
  27547,
  18584,
  30,
  24920,
  3,
  244,
  84],
 [2,
  885,
  7,
  48074,
  29,
  210,
  847,
  408,
  773,
  6,
  4112,
  196,
  877,
  6,
  2043,
  686,
  2,
  3100,
  288,
  5894],
 [2,
  11459,
  1793,
  1958,
  42,
  561,
  18,
  4,
  1314,
  5,
  2,
  19738,
  15875,
  37192,
  15,
  7845,
  95,
  5084,
  390,
  4757],
 [7,
  68,
  5,
  2,
  2044,
  11816,
  448,
  9,
  620,
  7311,
  1343,
  2662,
  79,
  2338,
  2247,
  27548,
  30,
  24921,
  335,
  48,
  43,
  6029,
  26,
  39],
 [254,
  16,
  2349,
  115,
  6,
  726,
  8,
  3426,
  3,
  534,
  7,
  87,
  70,
  2,
  2512,
  3179,
  2,
  3728,
  18585,
  11460],
 [1640,
  648,
  7,
  4160,
  969,
  118,
  29,
  444,
  531,
  344,
  18586,
  8,
  2851,
  1096,
  6800,
  87,
  20,
  5661,
  32,
  62,
  11461],
 [2,
  403,
  5,
  2,
  602,
  11458,
  587,
  1549,
  2423,
  2,
  133,
  1903,
  569,
  2852,
  9,
  31418,
  154,
  154,
  8787,
  98,
  110,
  27549,
  26,
  48075],
 [275,
  1220,
  21,
  236,
  4,
  614,
  1409,
  3,
  133,
  131,
  1007,
  15,
  505,
  217,
  2646,
  4308,
  845,
  181,
  113,
  69],
 [4, 383, 885, 615, 96, 54, 7, 2384, 725, 19, 508],
 [2,
  4991,
  31419,
  7448,
  11817,
  2120,
  195,
  6423,
  78,
  2364,
  11462,
  3033,
  7,
  4,
  264,
  3260,
  697,
  3,
  2,
  6090],
 [2,
  210,
  1333,
  343,
  4,
  10256,
  487,
  1841,
  103,
  82,
  500,
  78,
  1299,
  13,
  917,
  663],
 [2,
  274,
  277,
  1727,
  22,
  14617,
  10,
  7079,
  5,
  844,
  2932,
  1244,
  1019,
  3,
  654,
  31,
  150,
  13,
  814],
 [61,
  8,
  49,
  217,
  31420,
  159,
  2,
  969,
  12632,
  249,
  1007,
  9,
  123,
  252,
  3895,
  6,
  4,
  1967,
  297,
  7710,
  9,
  76,
  583,
  93,
  1065],
 [2,
  892,
  207,
  70,
  2,
  1918,
  650,
  1998,
  9,
  2,
  1149,
  789,
  7,
  1589,
  318,
  3510,
  5,
  3463,
  11113,
  8975,
  10,
  244,
  7,
  2820],
 [2, 20, 14, 22, 760, 63, 50, 105, 1598, 114, 76, 11114, 192, 415, 6, 2424],
 [31421,
  15234,
  63,
  7708,
  5181,
  2,
  823,
  10,
  2931,
  2560,
  2187,
  6,
  87,
  585,
  13,
  427,
  72],
 [48076, 1469, 4381, 1929, 75, 1760, 13074, 1061, 3, 2620, 2, 1273],
 [358,
  1235,
  7,
  28,
  6878,
  20,
  149,
  20,
  50,
  216,
  1816,
  67,
  30,
  28,
  156,
  2,
  11818,
  13571],
 [40,
  15235,
  37193,
  520,
  26,
  2,
  17527,
  9,
  2903,
  145,
  56,
  15876,
  74,
  227,
  143,
  404,
  89,
  1129,
  40,
  4,
  4944,
  13075,
  56,
  1999,
  3149,
  2728,
  26,
  21153,
  3464,
  7,
  19739,
  969,
  1528,
  1000,
  150,
  6,
  96,
  1418,
  6,
  1465,
  56,
  6,
  261,
  3223],
 [3126,
  48077,
  1061,
  13,
  1837,
  3,
  126,
  70,
  277,
  599,
  8152,
  1306,
  22811,
  288,
  2456,
  48078,
  4696,
  3,
  643,
  2072,
  983],
 [297,
  7,
  4453,
  118,
  29,
  3362,
  32,
  62,
  153,
  7,
  2,
  14062,
  5,
  4,
  307,
  45,
  22,
  12207,
  101,
  19740],
 [1800,
  5,
  19733,
  1047,
  241,
  1571,
  123,
  93,
  21,
  1261,
  487,
  70,
  10824,
  22805,
  2,
  3756,
  3778],
 [1303,
  5746,
  9,
  33,
  5291,
  8,
  900,
  20,
  2904,
  48079,
  19741,
  27,
  3729,
  15877,
  10824,
  9,
  21,
  615,
  506,
  251,
  2663,
  54],
 [452,
  45,
  3730,
  2,
  89,
  1129,
  968,
  26,
  21153,
  3464,
  7,
  969,
  16,
  1079,
  2,
  305,
  15,
  4,
  464,
  5,
  711,
  134,
  582,
  465,
  6801],
 [24922,
  6,
  1967,
  2879,
  22812,
  1397,
  5,
  8976,
  2710,
  13,
  557,
  10002,
  4382,
  5291,
  6,
  8313,
  217,
  3224,
  7,
  60,
  1572],
 [4113,
  182,
  404,
  2,
  4193,
  4945,
  548,
  528,
  27,
  2,
  444,
  13563,
  2,
  6515,
  528,
  42,
  18,
  6248,
  26,
  2,
  6802,
  11819,
  15236,
  2457,
  7,
  2505],
 [4,
  4018,
  32,
  62,
  1726,
  70,
  14618,
  4,
  376,
  5476,
  83,
  37194,
  5535,
  101,
  2889,
  3,
  2621,
  78,
  4,
  4263,
  1072],
 [188, 5, 2, 621, 7846, 31422, 850, 2, 5662, 8, 2, 68, 722, 3, 1248],
 [2729, 3465, 2222, 12633, 5593, 35, 3670, 2163, 63, 648],
 [37195,
  297,
  1794,
  48080,
  48081,
  48082,
  15,
  189,
  17528,
  3706,
  5,
  6803,
  5,
  2932,
  50,
  98,
  284,
  53,
  3,
  37,
  69,
  7,
  2402,
  10,
  203,
  2134],
 [48083,
  223,
  4309,
  4526,
  37196,
  8,
  105,
  818,
  3059,
  3,
  898,
  4852,
  3,
  2,
  1657,
  2933,
  13,
  507],
 [2,
  1617,
  335,
  2,
  82,
  2132,
  5,
  29,
  9157,
  2007,
  1617,
  268,
  335,
  8,
  5594,
  31,
  37197,
  1337,
  996,
  5,
  2,
  37198],
 [2,
  740,
  642,
  5132,
  3757,
  2,
  31423,
  31424,
  31,
  2,
  2188,
  5,
  37199,
  45,
  8,
  19742,
  35,
  76,
  26,
  155,
  10,
  2,
  5814,
  5,
  2,
  6424,
  1266],
 [2,
  7711,
  1096,
  5,
  2,
  37200,
  1817,
  31422,
  11,
  5662,
  335,
  2,
  68,
  722,
  170,
  1595,
  35,
  5412,
  335,
  22,
  5135,
  408,
  7,
  2,
  9341,
  752],
 [2,
  3728,
  1359,
  2410,
  3,
  491,
  692,
  27,
  4,
  545,
  1020,
  740,
  5,
  491,
  456,
  7,
  917,
  20,
  33,
  292,
  389,
  152,
  2,
  8153,
  3,
  138,
  10,
  960],
 [13572,
  48084,
  75,
  4347,
  3,
  8788,
  3363,
  6516,
  6,
  18587,
  37201,
  3705,
  103,
  11115,
  29,
  14063,
  238,
  20,
  29,
  1599,
  40,
  74,
  22,
  82,
  1539,
  10,
  579,
  2,
  5136],
 [48,
  25,
  10257,
  8,
  12208,
  30,
  142,
  1801,
  5,
  3006,
  159,
  1160,
  7988,
  6,
  5240,
  5,
  13573,
  2339,
  19,
  2374,
  98,
  18,
  10,
  12],
 [2,
  24923,
  22,
  864,
  35,
  24924,
  10,
  506,
  278,
  337,
  599,
  29,
  2588,
  8465,
  5,
  56,
  18588,
  17529,
  155],
 [2, 21154, 448, 4, 24925, 225, 1618, 4, 3812],
 [2,
  3729,
  529,
  5358,
  8,
  1144,
  4,
  7581,
  11116,
  9,
  89,
  71,
  1100,
  178,
  2,
  19743,
  1852,
  2528],
 [2,
  48085,
  11,
  2126,
  12,
  5241,
  1078,
  3757,
  13,
  2268,
  194,
  4,
  593,
  128,
  1036,
  760,
  19744,
  79,
  900,
  3,
  1165,
  4,
  748,
  8466,
  3,
  80,
  14,
  177],
 [2,
  3925,
  1619,
  4348,
  1878,
  59,
  100,
  6,
  47,
  3707,
  173,
  24,
  674,
  83,
  6346,
  5663,
  26,
  2,
  3101],
 [2,
  6424,
  19745,
  113,
  798,
  818,
  2905,
  506,
  251,
  310,
  87,
  312,
  50,
  2777,
  3,
  490,
  2,
  2589,
  13,
  2261],
 [2,
  476,
  8,
  2988,
  3,
  31425,
  901,
  7,
  1427,
  5,
  211,
  100,
  595,
  49,
  654,
  13076,
  3,
  6346,
  2791,
  864,
  26,
  47,
  1037,
  2457],
 [81,
  16,
  2,
  683,
  2969,
  7,
  2,
  91,
  2223,
  31426,
  63,
  7,
  809,
  3,
  2,
  1176,
  104,
  1138,
  285,
  781,
  2791,
  26,
  47,
  1050,
  6879],
 [3062,
  11463,
  41,
  378,
  194,
  2,
  760,
  45,
  2458,
  869,
  5,
  4697,
  238,
  586,
  1251,
  2403,
  7,
  47,
  478,
  1930],
 [46, 37, 191, 70, 180, 10, 211, 470, 433, 7194, 598, 274],
 [712,
  48086,
  61,
  16,
  95,
  525,
  529,
  6171,
  9,
  142,
  2506,
  15,
  12634,
  3440,
  18589],
 [7195,
  147,
  3,
  475,
  39,
  1262,
  27550,
  111,
  119,
  2,
  31422,
  1959,
  2483,
  63,
  70,
  2,
  82,
  2711,
  22,
  31427],
 [48087,
  45,
  26,
  37,
  388,
  1919,
  20,
  4,
  205,
  187,
  332,
  3225,
  8,
  63,
  3,

In [18]:
input_sequences = []
for line in data['short_description']:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [19]:
input_sequences

[[134, 926],
 [134, 926, 63],
 [134, 926, 63, 14],
 [134, 926, 63, 14, 8],
 [134, 926, 63, 14, 8, 137],
 [134, 926, 63, 14, 8, 137, 444],
 [134, 926, 63, 14, 8, 137, 444, 3],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018, 77],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018, 77, 2036],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018, 77, 2036, 53],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018, 77, 2036, 53, 15],
 [134, 926, 63, 14, 8, 137, 444, 3, 5238, 212, 2018, 77, 2036, 53, 15, 2],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131,
  2888],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131,
  2888,
  10],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131,
  2888,
  10,
  2],
 [134,
  926,
  63,
  14,
  8,
  137,
  444,
  3,
  5238,
  212,
  2018,
  77,
  2036,
  53,
  15,
  2,
  27536,
  310,
  8784,
  5,
  2,
  49,
  27537,
  2,
  133,
  131,
  2888,
  10,
  2,
  482],
 [50, 22],
 [50, 22, 19731],
 [50, 22, 19731, 35],
 [50, 22, 19731, 35, 2951],
 [50, 22, 19731, 35, 2951, 6],
 [50, 22, 19731, 35, 2951, 6, 3098],
 [50, 22, 19731, 35, 2951, 6, 3098, 40],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2, 115],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2, 115, 5],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2, 115, 5, 2],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2, 115, 5, 2, 5743],
 [50, 22, 19731, 35, 2951, 6, 3098, 40, 50, 5659, 3, 2, 115, 5, 2, 5743, 70],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637,
  519],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637,
  519,
  7],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637,
  519,
  7,
  1095],
 [50,
  22,
  19731,
  35,
  2951,
  6,
  3098,
  40,
  50,
  5659,
  3,
  2,
  115,
  5,
  2,
  5743,
  70,
  2,
  8311,
  295,
  3,
  2,
  133,
  131,
  16637,
  519,
  7,
  1095,
  1172],
 [374, 12],
 [374, 12, 21],
 [374, 12, 21, 4],
 [374, 12, 21, 4, 947],
 [374, 12, 21, 4, 947, 12],
 [374, 12, 21, 4, 947, 12, 93],
 [374, 12, 21, 4, 947, 12, 93, 523],
 [374, 12, 21, 4, 947, 12, 93, 523, 38],
 [374, 12, 21, 4, 947, 12, 93, 523, 38, 98],
 [374, 12, 21, 4, 947, 12, 93, 523, 38, 98, 18],
 [374, 12, 21, 4, 947, 12, 93, 523, 38, 98, 18, 4988],
 [5591, 245],
 [5591, 245, 1834],
 [5591, 245, 1834, 53],
 [5591, 245, 1834, 53, 15871],
 [5591, 245, 1834, 53, 15871, 13],
 [5591, 245, 1834, 53, 15871, 13, 28],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6, 50],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6, 50, 13559],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6, 50, 13559, 58],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6, 50, 13559, 58, 11],
 [5591, 245, 1834, 53, 15871, 13, 28, 37175, 24911, 6, 50, 13559, 58, 11, 22],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409,
  14059],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409,
  14059,
  7],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409,
  14059,
  7,
  31410],
 [5591,
  245,
  1834,
  53,
  15871,
  13,
  28,
  37175,
  24911,
  6,
  50,
  13559,
  58,
  11,
  22,
  2878,
  47,
  3440,
  15,
  4,
  1777,
  31409,
  14059,
  7,
  31410,
  3058],
 [3032, 4989],
 [3032, 4989, 869],
 [3032, 4989, 869, 2373],
 [3032, 4989, 869, 2373, 2776],
 [3032, 4989, 869, 2373, 2776, 6694],
 [3032, 4989, 869, 2373, 2776, 6694, 48042],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814, 5131],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814, 5131, 56],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814, 5131, 56, 6],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814, 5131, 56, 6, 7577],
 [3032, 4989, 869, 2373, 2776, 6694, 48042, 5, 11814, 5131, 56, 6, 7577, 56],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313,
  911],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313,
  911,
  3045],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313,
  911,
  3045,
  500],
 [3032,
  4989,
  869,
  2373,
  2776,
  6694,
  48042,
  5,
  11814,
  5131,
  56,
  6,
  7577,
  56,
  4,
  2259,
  70,
  280,
  5,
  2,
  1313,
  911,
  3045,
  500,
  2362],
 [2, 10818],
 [2, 10818, 69],
 [2, 10818, 69, 125],
 [2, 10818, 69, 125, 307],
 [2, 10818, 69, 125, 307, 22],
 [2, 10818, 69, 125, 307, 22, 393],
 [2, 10818, 69, 125, 307, 22, 393, 356],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665, 1777],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665, 1777, 1072],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665, 1777, 1072, 13],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665, 1777, 1072, 13, 905],
 [2, 10818, 69, 125, 307, 22, 393, 356, 26, 2, 665, 1777, 1072, 13, 905, 74],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845,
  56],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845,
  56,
  1285],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845,
  56,
  1285,
  1303],
 [2,
  10818,
  69,
  125,
  307,
  22,
  393,
  356,
  26,
  2,
  665,
  1777,
  1072,
  13,
  905,
  74,
  22,
  208,
  826,
  752,
  70,
  56,
  156,
  845,
  56,
  1285,
  1303,
  63],
 [1545, 9],
 [1545, 9, 429],
 [1545, 9, 429, 12],
 [1545, 9, 429, 12, 29],
 [1545, 9, 429, 12, 29, 3441],
 [1545, 9, 429, 12, 29, 3441, 10],
 [1545, 9, 429, 12, 29, 3441, 10, 49],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043, 386],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043, 386, 2454],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043, 386, 2454, 2170],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043, 386, 2454, 2170, 5534],
 [1545, 9, 429, 12, 29, 3441, 10, 49, 14609, 48043, 386, 2454, 2170, 5534, 20],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74,
  3895],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74,
  3895,
  53],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74,
  3895,
  53,
  29],
 [1545,
  9,
  429,
  12,
  29,
  3441,
  10,
  49,
  14609,
  48043,
  386,
  2454,
  2170,
  5534,
  20,
  74,
  3895,
  53,
  29,
  884],
 [33, 65],
 [33, 65, 545],
 [33, 65, 545, 4],
 [33, 65, 545, 4, 310],
 [33, 65, 545, 4, 310, 54],
 [33, 65, 545, 4, 310, 54, 4235],
 [33, 65, 545, 4, 310, 54, 4235, 202],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189, 184],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189, 184, 70],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189, 184, 70, 2],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189, 184, 70, 2, 1617],
 [33, 65, 545, 4, 310, 54, 4235, 202, 487, 696, 189, 184, 70, 2, 1617, 14610],
 [33,
  65,
  545,
  4,
  310,
  54,
  4235,
  202,
  487,
  696,
  189,
  184,
  70,
  2,
  1617,
  14610,
  2],
 [33,
  65,
  545,
  4,
  310,
  54,
  4235,
  202,
  487,
  696,
  189,
  184,
  70,
  2,
  1617,
  14610,
  2,
  133],
 [33,
  65,
  545,
  4,
  310,
  54,
  4235,
  202,
  487,
  696,
  189,
  184,
  70,
  2,
  1617,
  14610,
  2,
  133,
  131],
 [33,
  65,
  545,
  4,
  310,
  54,
  4235,
  202,
  487,
  696,
  189,
  184,
  70,
  2,
  1617,
  14610,
  2,
  133,
  131,
  4346],
 [7, 48044],
 [7, 48044, 633],
 [7, 48044, 633, 15230],
 [7, 48044, 633, 15230, 8617],
 [7, 48044, 633, 15230, 8617, 4017],
 [7, 48044, 633, 15230, 8617, 4017, 415],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2, 271],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2, 271, 5],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2, 271, 5, 15231],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2, 271, 5, 15231, 6],
 [7, 48044, 633, 15230, 8617, 4017, 415, 10533, 15, 2, 271, 5, 15231, 6, 8618],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4,
  33],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4,
  33,
  9153],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4,
  33,
  9153,
  1537],
 [7,
  48044,
  633,
  15230,
  8617,
  4017,
  415,
  10533,
  15,
  2,
  271,
  5,
  15231,
  6,
  8618,
  3,
  304,
  4,
  33,
  9153,
  1537,
  288],
 [205, 187],
 [205, 187, 648],
 [205, 187, 648, 118],
 [205, 187, 648, 118, 2],
 [205, 187, 648, 118, 2, 27538],
 [205, 187, 648, 118, 2, 27538, 5],
 [205, 187, 648, 118, 2, 27538, 5, 2],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2, 133],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2, 133, 1903],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2, 133, 1903, 19],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2, 133, 1903, 19, 69],
 [205, 187, 648, 118, 2, 27538, 5, 2, 1018, 734, 3, 2, 133, 1903, 19, 69, 42],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116,
  6],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116,
  6,
  92],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116,
  6,
  92,
  3954],
 [205,
  187,
  648,
  118,
  2,
  27538,
  5,
  2,
  1018,
  734,
  3,
  2,
  133,
  1903,
  19,
  69,
  42,
  18,
  4,
  315,
  37176,
  10819,
  5,
  1116,
  6,
  92,
  3954,
  399],
 [7985, 32],
 [7985, 32, 171],
 [7985, 32, 171, 343],
 [7985, 32, 171, 343, 1304],
 [7985, 32, 171, 343, 1304, 27],
 [7985, 32, 171, 343, 1304, 27, 505],
 [7985, 32, 171, 343, 1304, 27, 505, 1610],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045, 45],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045, 45, 90],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045, 45, 90, 3],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045, 45, 90, 3, 339],
 [7985, 32, 171, 343, 1304, 27, 505, 1610, 2518, 48045, 45, 90, 3, 339, 4],
 [7985,
  32,
  171,
  343,
  1304,
  27,
  505,
  1610,
  2518,
  48045,
  45,
  90,
  3,
  339,
  4,
  360],
 [7985,
  32,
  171,

In [20]:
max_len = max(len(x) for x in input_sequences)

In [21]:
max_len

246

In [22]:
input = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [27]:
# All row 
X = input[:,:-1]
# Final word of each row
y = np.array(input[:,-1])

### Train Test split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
X_train.shape, y_train.shape

((3150234, 245), (3150234,))

In [30]:
max_len = X.shape[1]

### Create a model

In [32]:
model = Sequential([
    Embedding(vocab_size, 128, input_length=max_len),
    LSTM(256),
    Dense(vocab_size, activation='softmax')
])

e:\GenAI\projects\next-word-prediction-using-lstm\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [33]:
model.compile(
    loss='sparse_categorical_crossentropy', 
    optimizer='adam', 
    metrics=['accuracy']
    )

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [34]:
model.build(input_shape=(None, max_len))

In [35]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 245, 128)       │    11,455,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 89495)          │    23,000,215 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34,849,815 (132.94 MB)

 Trainable params: 34,849,815 (132.94 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
  266/98445 ━━━━━━━━━━━━━━━━━━━━ 46:09:00 2s/step - accuracy: 0.0408 - loss: 9.5032

In [ ]:
model.save('nextword.h5')

In [ ]:
with open('tokenzier.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)